---
title: "Lottery_clearedCode"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```
```
```{r library}
library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(factoextra)
library(rlang)
library(xtable)
```
```
```
```{r functions}
#Function inputting the price probability distribution. Randomly sample from the probability distribution and stop when the prize is bigger than 600. Return the number of times it takes to get 600 and the prize in the last draw.
random.sample <- function(x,y) {
  success <- FALSE
  result<-0
  time<-0
  while (!success) {
    i <- sample(x, 1,replace = T,prob = y)
    time=time+1
    if(i>=600){
      success<-TRUE
    }else{
      result=result+i
    }
  }
  return(c(time,result))
}

#Function for Scratch-off stochastic model. Input the all the prizes won for a single player and the times wanted to run the stochastic model. Return the out-of-pocket cost for each run.
random.sample.times<-function(tempName,Time){
  sumReturn<-numeric(0)
  tempName$NumberToWin=0
  tempName$Won=0
  tempName$outPocket=0
  b<-0
  while(b < Time){
    for(a in 1:nrow(tempName)){
      if(tempName[a,]$Cost==2){
           temp<-random.sample(prize,lotteryProb[lotteryProb$Cost==2,-(1:2)])
           tempName[a,]$NumberToWin<-temp[1]
           tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$Cost==3){
           temp<-random.sample(prize,lotteryProb[lotteryProb$Cost==3,-(1:2)])
           tempName[a,]$NumberToWin<-temp[1]
           tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$Cost==5){
            temp<-random.sample(prize,lotteryProb[lotteryProb$Cost==5,-(1:2)])
            tempName[a,]$NumberToWin<-temp[1]
            tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$Cost==10){
             temp<-random.sample(prize,lotteryProb[lotteryProb$Cost==10,-(1:2)])
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$Cost==20){
             temp<-random.sample(prize,lotteryProb[lotteryProb$Cost==20,-(1:2)])
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$Cost==30){
             temp<-random.sample(prize,lotteryProb[lotteryProb$Cost==30,-(1:2)])
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }
    }
    tempName<-tempName%>%mutate(outPocket=NumberToWin*Cost-Won-PrizeAmount)
    sumReturn<-append(sumReturn,-sum(tempName$outPocket))
    b=b+1
}
  return(sumReturn)
}

#Function for Pick 4 lottery stochastic model. Input the all the prizes won for a single player and the times wanted to run the stochastic model. Return the out-of-pocket cost for each run.
pick4Alg<-function(tempName,Time){
  sumReturn<-numeric(0)
  tempName$NumberToWin=0
  tempName$Won=0
  tempName$outPocket=0
  b<-0
  while(b < Time){
    for(a in 1:nrow(tempName)){
      if(tempName[a,]$PrizeAmount==5000){
           temp<-random.sample(c(5000,0),c(1/10000,1-1/10000))
           tempName[a,]$NumberToWin<-temp[1]
           tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==1200){
           temp<-random.sample(c(1200,0),c(1/2500,1-1/2500))
           tempName[a,]$NumberToWin<-temp[1]
           tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==800){
            temp<-random.sample(c(800,0),c(6/10000,1-6/10000))
            tempName[a,]$NumberToWin<-temp[1]
            tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==3100|tempName[a,]$PrizeAmount==600){
             temp<-random.sample(c(3100,600,0),c(1/10000,3/10000,1-1/10000-3/10000))
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==2900){
             temp<-random.sample(c(2900,400,0),c(1/10000,5/10000,1-1/10000-5/10000))
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==2700){
             temp<-random.sample(c(2700,200,0),c(1/10000,11/10000,1-1/10000-11/10000))
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==2600){
             temp<-random.sample(c(2600,100,0),c(1/10000,23/10000,1-1/10000-23/10000))
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==2500){
             temp<-random.sample(c(2500,0),c(1/10000,1-1/10000))/2
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }
    }
    tempName<-tempName%>%mutate(outPocket=NumberToWin*Cost-Won-PrizeAmount)
    sumReturn<-append(sumReturn,-sum(tempName$outPocket))
    b=b+1
}
  return(sumReturn)
}

#Function for Mega Millions lottery stochastic model. Input the all the prizes won for a single player and the times wanted to run the stochastic model. Return the out-of-pocket cost for each run.
MegaAlg<-function(tempName,Time){
  megaplier_number = c(2,3,4,5)
  megaplier_prob = c(1/3,1/2.5,1/5,1/15)
  
  AllProb = c(1/302575350,1/12607306,1/931001,1/38792,1/14547,1/606,1/693,1/89,1/37,1-(1/302575350+1/12607306+1/931001+1/38792+1/14547+1/606+1/693+1/89+1/37))
  X1Prize = c(1000002,1000000,10000,500,200,10,10,4,2,0)
  
  X2Prize = c(2000002,2000000,20000,1000,400,20,20,8,4,0)

  X3Prize = c(3000002,3000000,30000,1500,600,30,30,12,6,0)
  
  X4Prize = c(4000002,4000000,40000,2000,800,40,40,16,8,0)
  
  X5Prize = c(5000002,5000000,50000,2500,1000,50,50,20,10,0)
  
  sumReturn<-numeric(0)
  tempName$NumberofCost=0
  tempName$Won=0
  tempName$outPocket=0
  b<-0
  while(b < Time){
    for(a in 1:nrow(tempName)){
      if(tempName[a,]$PrizeAmount%in%c(1000000,10000)){
        #When multiplier == 1
        temp<-random.sample(X1Prize,AllProb)
        tempName[a,]$NumberofCost<-temp[1]*2
        tempName[a,]$Won<-temp[2]
      }else{
        multiplier = sample(megaplier_number,1,replace = TRUE,prob = megaplier_prob)
        if(multiplier == 2){
           temp<-random.sample(X2Prize,AllProb)
           tempName[a,]$NumberofCost<-temp[1]*3
           tempName[a,]$Won<-temp[2]
        }else if(multiplier == 3){
           temp<-random.sample(X3Prize,AllProb)
           tempName[a,]$NumberofCost<-temp[1]*3
           tempName[a,]$Won<-temp[2]
        }else if(multiplier == 4){
           temp<-random.sample(X3Prize,AllProb)
           tempName[a,]$NumberofCost<-temp[1]*3
           tempName[a,]$Won<-temp[2]
        }else if(multiplier == 5){
           temp<-random.sample(X3Prize,AllProb)
           tempName[a,]$NumberofCost<-temp[1]*3
           tempName[a,]$Won<-temp[2]
        }
      }
    }
    tempName<-tempName%>%mutate(outPocket=NumberofCost-Won-PrizeAmount)
    sumReturn<-append(sumReturn,-sum(tempName$outPocket))
    b=b+1
}
  return(sumReturn)
}

#Function for Cash 5 lottery stochastic model. Input the all the prizes won for a single player and the times wanted to run the stochastic model. Return the out-of-pocket cost for each run.
Cash5Alg<-function(tempName,Time){
  sumReturn<-numeric(0)
  tempName$NumberToWin=0
  tempName$Won=0
  tempName$outPocket=0
  b<-0
  prize = c(50000,250,5,1,0)
  lotteryProb = c(1/749398,1/4163,1/119,1/10.5,1-(1/749398+1/4163+1/119+1/10.5))
  while(b < Time){
    for(a in 1:nrow(tempName)){
      temp<-random.sample(prize,lotteryProb)
      tempName[a,]$NumberToWin<-temp[1]
      tempName[a,]$Won<-temp[2]
    }
    tempName<-tempName%>%mutate(outPocket=NumberToWin*1-Won-PrizeAmount)
    sumReturn<-append(sumReturn,-sum(tempName$outPocket))
    b=b+1
}
  return(sumReturn)
}

#Function for Powerball lottery stochastic model. Input the all the prizes won for a single player and the times wanted to run the stochastic model. Return the out-of-pocket cost for each run.
PowerAlg<-function(tempName,Time){
  
  AllProb = c(1/292201338,1/11688054,1/9131291,1/36525,1/14494,1/580,1/701,1/92,1/38,1-(1/292201338+1/11688054+1/9131291+1/36525+1/14494+1/580+1/701+1/92+1/38))
  X1Prize = c(1000001,1000000,50000,100,100,7,7,4,4,0)
  
  sumReturn<-numeric(0)
  tempName$NumberofCost=0
  tempName$Won=0
  tempName$outPocket=0
  b<-0
  while(b < Time){
    for(a in 1:nrow(tempName)){
        #When multiplier == 1
        temp<-random.sample(X1Prize,AllProb)
        tempName[a,]$NumberofCost<-temp[1]*2
        tempName[a,]$Won<-temp[2]
    }
    tempName<-tempName%>%mutate(outPocket=NumberofCost-Won-PrizeAmount)
    sumReturn<-append(sumReturn,-sum(tempName$outPocket))
    b=b+1
}
  return(sumReturn)
}
```
```
```
```{r data_processing}
#Read Data and add fullname
load("Lottery_data.RData")
beforelottery$Fullname<-paste(beforelottery$Claimant_FName,beforelottery$Claimant_MName,beforelottery$Claimant_LName)
```
```
```
```{r entropy and log cost}
#Calculate the entropy for all people
allPeople_onlycount<-beforelottery%>%group_by(Fullname)%>%summarise(count=n())
allPeople_unfiltered<-beforelottery%>%right_join(allPeople_onlycount,by="Fullname")
allPeople<-allPeople_unfiltered[is.na(allPeople_unfiltered$count)==FALSE,]
allPeople_store_count<-allPeople%>%group_by(Fullname,SellingRetailerName)%>%summarise(count=n())
allPeople<-allPeople%>%left_join(allPeople_store_count,by=c("Fullname","SellingRetailerName"))
allPeople_select<-allPeople%>%select(Fullname,SellingRetailerName,count.x,count.y)%>%rename("WinningCount"=count.x,"StoreCount"=count.y)
allPeople_select<-allPeople_select%>%unique()%>%mutate(possibility=StoreCount/(WinningCount))
allPeople_select<-allPeople_select%>%group_by(Fullname)%>%mutate(entropy=-sum(possibility*log(possibility)))

#Calculate the expected out of pocket
beforelottery_simulation<-beforelottery%>%mutate("Estimated money"= 1/0.001226816)
beforelottery_simulation<-beforelottery_simulation%>%group_by(Fullname)%>%mutate("Estimate total money"=sum(`Estimated money`)*14.32653*(1-0.6050788)-sum(PrizeAmount))
beforelottery_simulation<-beforelottery_simulation%>%mutate("Log Cost"=log10(max(1,`Estimate total money`,na.rm = T)))
beforelottery_simulation_selected<-beforelottery_simulation%>%select(Fullname,`Estimated money`,`Estimate total money`)%>%unique()%>%mutate("Log Cost"=log10(max(1,`Estimate total money`,na.rm = T)))

#Combine together
simulation_entropy<-beforelottery_simulation_selected%>%full_join(allPeople_select,by="Fullname")

#Graph
simulation_entropy%>%ggplot(aes(x=entropy,y=`Log Cost`))+geom_point()+ggtitle("Log Cost vs Entropy")+xlab("Entropy")+ylab("Log Cost")
```
```
```
```{r Get the top Nine outliers}
simulation_entropy_unique<-simulation_entropy[!duplicated(simulation_entropy$Fullname),]
topNine<- simulation_entropy_unique[order(simulation_entropy_unique$entropy+simulation_entropy_unique$`Log Cost`,decreasing = T),]%>%head(9)
```
```
```
```{r Stochestic model representative lotteries information}
prize<-c(10000000,4000000,1000000,250000,100000,50000,20000,10000,5000,4000,2500,2000,1000,500,400,300,200,150,100,60,50,40,30,25,20,15,10,5,4,3,2,0)
lotteryProb<-read_xlsx("lotteryProb.xlsx")
prizePick4<-c(5000,3100,2900,2700,2600,1200,800,600,400,300,200,100,52,50,40,26,0)
Pick4Prob = read_xlsx("Pick4Prob.xlsx")

Pick3Prob<-data_frame(Gamename=c("Pick 3"),Prize=c(1000,500,160,80,330,80,290,40,500,500,50,50,40,10,18,0),Prob=c(91*(1/1000)^2*(999/1000)^12,1/1000,1/333.3,1/166.7,1/1000,1/333.3,1/1000,1/166.7,1/1/333.3,1/166.7,1/100,1/100,1/166.67,1/83.33,1/125,1-(91*(1/1000)^2*(999/1000)^12+1/1000+1/333.3+1/166.7+1/1000+1/333.3+1/1000+1/166.7+1/1/333.3+1/166.7+1/100+1/100+1/166.67+1/83.33+1/125)))
```
```
```
```{r Read TopNine data including detailed information about the lotteris they played}
Curtis = read_xlsx("Curtis.xlsx")
James = read_xlsx("James.xlsx")
Tawfik = read_xlsx("Tawfik.xlsx")
Bobby = read_xlsx("Bobby.xlsx")
Paul = read_xlsx("Paul.xlsx")
Betty = read_xlsx("Betty.xlsx")
Beverly = read_xlsx("Beverly.xlsx")
David = read_xlsx("David.xlsx")
Margaret = read_xlsx("Margaret.xlsx")
```
```
```
```{r simulation}
#Run the simulation on the nine outliers
set.seed(50000)
Curtis$NumberToWin=0
Curtis$Won=0
Curtis$outPocket=0
JamesSumReturn<-random.sample.times(James[James$GameName!="Pick 4" & James$GameName!="Pick 3" & James$GameName!="Wild 8s",],1000)
CurtisSumReturn<-random.sample.times(Curtis[Curtis$GameName!="Pick 4" & Curtis$GameName!="Pick 3" & Curtis$GameName!="Wild 8s",],1000)+pick4Alg(Curtis[Curtis$GameName=="Pick 4" | Curtis$GameName=="Pick 3" | Curtis$GameName=="Wild 8s",],1000)
BobbySumReturn<-random.sample.times(Bobby[Bobby$GameName!="Pick 4" & Bobby$GameName!="Pick 3" & Bobby$GameName!="Wild 8s",],1000)
PaulSumReturn<-random.sample.times(Paul[Paul$GameName!="Pick 4" & Paul$GameName!="Pick 3" & Paul$GameName!="Wild 8s",],1000)+pick4Alg(Paul[Paul$GameName=="Pick 4" | Paul$GameName=="Pick 3" | Paul$GameName=="Wild 8s",],1000)
BettySumReturn<-random.sample.times(Betty[Betty$GameName!="Pick 4" & Betty$GameName!="Pick 3" & Betty$GameName!="Wild 8s",],1000)+pick4Alg(Betty[Betty$GameName=="Pick 4" | Betty$GameName=="Pick 3" | Betty$GameName=="Wild 8s",],1000)
BeverlySumReturn<-random.sample.times(Beverly[Beverly$GameName!="Pick 4" & Beverly$GameName!="Pick 3" & Beverly$GameName!="Wild 8s",],1000)
DavidSumReturn<-random.sample.times(David[David$GameName!="Pick 4" & David$GameName!="Pick 3" & David$GameName!="Wild 8s" & David$GameName!="Mega Millions",],1000) + MegaAlg(David[David$GameName=="Mega Millions",],1000)
MargaretSumReturn<-random.sample.times(Margaret[Margaret$GameName!="Pick 4" & Margaret$GameName!="Pick 3" & Margaret$GameName!="Wild 8s",],1000)+pick4Alg(Margaret[Margaret$GameName=="Pick 4" | Margaret$GameName=="Pick 3" | Margaret$GameName=="Wild 8s",],1000)
TawfikSumReturn<-random.sample.times(Tawfik[Tawfik$GameName!="Pick 4" & Tawfik$GameName!="Pick 3" & Tawfik$GameName!="Wild 8s",],1000)+pick4Alg(Tawfik[Tawfik$GameName=="Pick 4" | Tawfik$GameName=="Pick 3" | Tawfik$GameName=="Wild 8s",],1000)
```
```
```
```{r Combine topNine out-of-pocket into a dataframe}
#Calculate some basic stats like 10%, 90% percentile, mean, etc.
topNineSumReturn<-data_frame(Name=c("Winner 1","Winner 2","Winner 3","Winner 4","Winner 5","Winner 6","Winner 7","Winner 8","Winner 9"),"mean Instant"=c(mean(JamesSumReturn),mean(TawfikSumReturn),mean(CurtisSumReturn),mean(BobbySumReturn),mean(PaulSumReturn),mean(BettySumReturn),mean(BeverlySumReturn),mean(DavidSumReturn),mean(MargaretSumReturn)),"Minimum Cost Instant"=c(max(JamesSumReturn),max(TawfikSumReturn),max(CurtisSumReturn),max(BobbySumReturn),max(PaulSumReturn),max(BettySumReturn),max(BeverlySumReturn),max(DavidSumReturn),max(MargaretSumReturn)),"Maximum Cost Instant"=c(min(JamesSumReturn),min(TawfikSumReturn),min(CurtisSumReturn),min(BobbySumReturn),min(PaulSumReturn),min(BettySumReturn),min(BeverlySumReturn),min(DavidSumReturn),min(MargaretSumReturn)),"10% Percentile Instant"=c(quantile(JamesSumReturn,0.1),quantile(TawfikSumReturn,0.1),quantile(CurtisSumReturn,0.1),quantile(BobbySumReturn,0.1),quantile(PaulSumReturn,0.1),quantile(BettySumReturn,0.1),quantile(BeverlySumReturn,0.1),quantile(DavidSumReturn,0.1),quantile(MargaretSumReturn,0.1)),"90% Percentile Instant"=c(quantile(JamesSumReturn,0.90),quantile(TawfikSumReturn,0.90),quantile(CurtisSumReturn,0.90),quantile(BobbySumReturn,0.90),quantile(PaulSumReturn,0.90),quantile(BettySumReturn,0.90),quantile(BeverlySumReturn,0.90),quantile(DavidSumReturn,0.90),quantile(MargaretSumReturn,0.90)))
```
```
```
```{r name corresponding dataframe}
winnerNumber <- c("Winner 1", "Winner 2", "Winner 3", "Winner 4", "Winner 5","Winner 6", "Winner 7", "Winner 8", "Winner 9")
Fullname <- c("James Randall Bray", "Tawfik Mohammad Sharafi", "Curtis NA Richardson", "Bobby Dean White", "Paul Julieus Kirkpatrick","Betty Carolynn Manning", "Beverly Ann Collins", "David Hughes Griffin", "Margaret A Howell")

nameForm <- data.frame(winnerNumber, Fullname)

print (nameForm)
```
```
```
```{r Filter winner wins>20 for K-means cluster}
#Select winners with wins bigger than 20
allPeople_select<-allPeople%>%select(Fullname,SellingRetailerName,count.x,count.y)%>%rename("WinningCount"=count.x,"StoreCount"=count.y)
allPeople_select<-allPeople_select%>%unique()%>%mutate(possibility=StoreCount/(WinningCount))
allPeople_select<-allPeople_select%>%group_by(Fullname)%>%mutate(entropy=-sum(possibility*log(possibility)))
allPeople_count=allPeople_select%>%group_by(WinningCount)%>%count(WinningCount)%>%mutate(SameWinCount=n)
allPeople_select=allPeople_select%>%left_join(allPeople_count,by="WinningCount")
bigWinner<-allPeople_select%>%filter(WinningCount>=20)%>%select(Fullname,SellingRetailerName,WinningCount,StoreCount,possibility,entropy)%>%rename(StoreWinCount=StoreCount)
bigWinner<-bigWinner%>%group_by(Fullname)%>%arrange(possibility)%>%mutate(HighestStoreProb=max(possibility))

#Get the top 5 most frequent visisted stores for each winner
bigWinner<-bigWinner%>%group_by(Fullname)%>%mutate(rank = rank(desc(possibility),ties.method = "random")) %>%arrange(rank)%>%ungroup()
bigWinner_pivoted<-bigWinner%>%pivot_wider(names_from = rank,values_from = possibility,id_cols = Fullname)
bigWinner_top5<-bigWinner_pivoted
bigWinner_top5$Rest = 0
for (a in 1:nrow(bigWinner_top5)){
  bigWinner_top5[a,]$Rest = sum(bigWinner_top5[a,7:87],na.rm = TRUE)
}
bigWinner_top5<-bigWinner_top5%>%rename("One"=`1`,"Two"=`2`,"Three"=`3`,"Four"=`4`,"Five"=`5`,"Six"=`6`)
bigWinner_top5<-bigWinner_top5%>%select(Fullname,One,Two,Three,Four,Five,Rest)
bigWinner_top5[is.na(bigWinner_top5)] <- 0
```
```
```
```{r see kmeans clusters:15, 20, 25}
#See the k
set.seed(50000)

mvtop5_15cluster<-kmeans(bigWinner_top5[,2:7], 15)
bigWinner_top5$cluster15 = as.factor(mvtop5_15cluster$cluster)

mvtop5_20cluster<-kmeans(bigWinner_top5[,2:7], 20)
bigWinner_top5$cluster20 = as.factor(mvtop5_20cluster$cluster)

mvtop5_25cluster<-kmeans(bigWinner_top5[,2:7], 25)
bigWinner_top5$cluster25 = as.factor(mvtop5_25cluster$cluster)
temp6<-bigWinner_top5%>%right_join(topNine,by = "Fullname")
temp6<-temp6%>%full_join(nameForm,by = "Fullname") 
temp6<-temp6[,c("winnerNumber","cluster15","cluster20","cluster25")]%>%rename("Fullname" = winnerNumber)
```
```
```
```{r see people in the two clusters which the top nine outliers are also in}
#Most top nine people cluster (color red in later graph)
redCluster = int(temp6[temp6$Fullname=="Winner 1",]$cluster25)
cluster25_red<-bigWinner_top5[bigWinner_top5$cluster25==redCluster,]
cluster25_red<-unique(unique(beforelottery%>%right_join(cluster25_red,by = "Fullname")%>%select(Fullname,SellingRetailerAddress,One,Two,Three,Four,Five,Rest, cluster15,cluster20,cluster25))%>%left_join(simulation_entropy,by="Fullname")%>%select(Fullname,One,Two,Three,Four,Five,Rest,cluster15,cluster20,cluster25,`Estimate total money`,`Log Cost`,WinningCount,entropy))

#Most top nine people cluster (color blue in later graph)
blueCluster = int(temp6[temp6$Fullname=="Winner 3",]$cluster25)
cluster25_blue<-bigWinner_top5[bigWinner_top5$cluster25==blueCluster,]
cluster25_blue<-unique(unique(beforelottery%>%right_join(cluster25_blue,by = "Fullname")%>%select(Fullname,SellingRetailerAddress,One,Two,Three,Four,Five,Rest,cluster15,cluster20,cluster25))%>%left_join(simulation_entropy,by="Fullname")%>%select(Fullname,One,Two,Three,Four,Five,Rest,cluster15,cluster20,cluster25,`Estimate total money`,`Log Cost`,WinningCount,entropy))
```
```
```
```{r graph for entropy and cost with clusters}
set.seed(5000)

#Graph in paper
ggplot()+geom_point(mapping=aes(x=simulation_entropy$entropy,y=simulation_entropy$`Log Cost`),color = "dark grey",alpha = 0.5,size = 0.7)+geom_point(mapping=aes(x=cluster25_red$entropy,y=cluster25_red$`Log Cost`),color="red")+geom_point(mapping=aes(x=cluster25_blue$entropy,y=cluster25_blue$`Log Cost`),color="blue")+ggtitle("Log Cost vs Entropy")+xlab("Entropy")+ylab("Log Cost") 

simulation_entropy_unique1<-simulation_entropy_unique%>%right_join(bigWinner_top5,by="Fullname")

#Graph with all clusters
ggplot()+geom_point(mapping=aes(x=simulation_entropy$entropy,y=simulation_entropy$`Log Cost`),color="white",size =0.5)+geom_point(mapping=aes(x=simulation_entropy_unique1$entropy,y=simulation_entropy_unique1$`Log Cost`,color=simulation_entropy_unique1$cluster25),size =0.5)+ggtitle("Log Cost vs Entropy")+xlab("Entropy")+ylab("Log Cost")+
  scale_colour_manual(guide="legend", breaks = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25),values = c("#8b4513","#228b22","#708090","#808000","#483d8b","#000080","#9acd32","#ff0000","#ffa500","#ffff00","#7cfc00","#8a2be2","#00ff7f","#dc143c","#00bfff","#0000ff","#da70d6","#ff7f50","#ff00ff","#1e90ff","#eee8aa","#b0e0e6","#ff1493","#7fffd4","#ffc0cb")) 
```
```
```
```{r create dataframe for the rest of winners in the cluster}

#Get the lottery details for rest of the plaers in the same cluster as the top nine people
beforelottery%>%right_join(cluster25_red,by = "Fullname")
topNine$Fullname
temp11<-data.frame(Paul$GameName,Paul$Cost)%>%rename("GameName"=Paul.GameName,"Cost"=Paul.Cost)
temp12<-data.frame(Curtis$GameName,Curtis$Cost)%>%rename("GameName"=Curtis.GameName,"Cost"=Curtis.Cost)
temp13<-data.frame(Tawfik$GameName,Tawfik$Cost)%>%rename("GameName"=Tawfik.GameName,"Cost"=Tawfik.Cost)
temp14<-data.frame(James$GameName,James$Cost)%>%rename("GameName"=James.GameName,"Cost"=James.Cost)
temp15<-data.frame(Bobby$GameName,Bobby$Cost)%>%rename("GameName"=Bobby.GameName,"Cost"=Bobby.Cost)
temp16<-data.frame(Betty$GameName,Betty$Cost)%>%rename("GameName"=Betty.GameName,"Cost"=Betty.Cost)
temp17<-data.frame(Beverly$GameName,Beverly$Cost)%>%rename("GameName"=Beverly.GameName,"Cost"=Beverly.Cost)
temp18<-data.frame(David$GameName,David$Cost)%>%rename("GameName"=David.GameName,"Cost"=David.Cost)
temp19<-data.frame(Margaret$GameName,Margaret$Cost)%>%rename("GameName"=Margaret.GameName,"Cost"=Margaret.Cost)

lotteryCost<-unique(rbind(temp11,temp12,temp13,temp14,temp15,temp16,temp17,temp18,temp19))

cluster25_red$Fullname

Reginald<-beforelottery[beforelottery$Fullname=="Reginald Keith Joyner",]%>%left_join(lotteryCost,by="GameName")

Reginald[Reginald$GameName=="$100 Million Cash Spectacular",]$Cost<-10
Reginald[Reginald$GameName=="$130 Million Blockbuster",]$Cost<-10

Penelope<-beforelottery[beforelottery$Fullname=="Penelope S Morgan",]%>%left_join(lotteryCost,by="GameName")
Penelope[Penelope$GameName=="$130 Million Blockbuster",]$Cost<-10
Penelope[Penelope$GameName=="Jumbo Bucks",]$Cost<-10

Hubert<-beforelottery[beforelottery$Fullname=="Hubert D Piver",]%>%left_join(lotteryCost,by="GameName")
Hubert[Hubert$GameName=="$100 Million Cash Spectacular",]$Cost<-10
Hubert[Hubert$GameName=="Jumbo Bucks",]$Cost<-10

Charles<-beforelottery[beforelottery$Fullname=="Charles Eugene Williams",]%>%left_join(lotteryCost,by="GameName")
Charles[Charles$GameName=="Super 7s",]$Cost<-5
Charles[Charles$GameName=="Jumbo Bucks",]$Cost<-10

Kevan<-beforelottery[beforelottery$Fullname=="Kevan Andrew Bytnar",]%>%left_join(lotteryCost,by="GameName")
Kevan[Kevan$GameName=="$200,000 Jackpot",]$Cost<-5

Eddie<-beforelottery[beforelottery$Fullname=="Eddie Dennis Beaver",]%>%left_join(lotteryCost,by="GameName")

Paul1<-beforelottery[beforelottery$Fullname=="Paul Jay Braun",]%>%left_join(lotteryCost,by="GameName")
Paul1[Paul1$GameName=="20X THE MONEY",]$Cost<-5

James1<-beforelottery[beforelottery$Fullname=="James Lynn Peachee",]%>%left_join(lotteryCost,by="GameName")

Paul2<-beforelottery[beforelottery$Fullname=="Paul Douglas Maxwell",]%>%left_join(lotteryCost,by="GameName")
Paul2[Paul2$GameName=="Jumbo Bucks",]$Cost<-10

Bernadette<-beforelottery[beforelottery$Fullname=="Bernadette Caldwell Mohamed",]%>%left_join(lotteryCost,by="GameName")

Howard<-beforelottery[beforelottery$Fullname=="Howard Brooks Helton",]%>%left_join(lotteryCost,by="GameName")
Howard[Howard$GameName=="$130 Million Blockbuster",]$Cost<-10
Howard[Howard$GameName=="Jumbo Bucks",]$Cost<-10
Howard[Howard$GameName=="$500 A WEEK FOR LIFE!",]$Cost<-10
Howard[Howard$GameName=="20X THE MONEY",]$Cost<-10
Howard[Howard$GameName=="Triple Tripler",]$Cost<-3
Howard[Howard$GameName=="Monte Carlo",]$Cost<-5

Latisha<-beforelottery[beforelottery$Fullname=="Latisha Tonette Cutler",]%>%left_join(lotteryCost,by="GameName")
Latisha[Latisha$GameName=="MONOPOLY MILLIONAIRES CLUB",]$Cost<-5
Latisha[Latisha$GameName=="$250,000 FORTUNE",]$Cost<-5
Latisha[Latisha$GameName=="MONOPOLY MILLIONAIRES CLUB",]$Cost<-5
Latisha[Latisha$GameName=="CAROLINA CASH",]$Cost<-5

Steven<-beforelottery[beforelottery$Fullname=="Steven W Morris",]%>%left_join(lotteryCost,by="GameName")
Steven[Steven$GameName=="$4,000,000 PLATINUM PAYOUT",]$Cost<-20

Cuarles<-beforelottery[beforelottery$Fullname=="Charles NA Alston",]%>%left_join(lotteryCost,by="GameName")
Cuarles[Cuarles$GameName=="TRIPLE PLAY",]$Cost<-5
```
```
```
```{r simulation for these people}
ReginaldSumReturn<-random.sample.times(Reginald[Reginald$GameName!="Pick 4" & Reginald$GameName!="Pick 3" & Reginald$GameName!="Wild 8s" & Reginald$GameName!="Mega Millions",],1000)+pick4Alg(Reginald[Reginald$GameName=="Pick 4" | Reginald$GameName=="Pick 3" | Reginald$GameName=="Wild 8s",],1000) + MegaAlg(Reginald[Reginald$GameName=="Mega Millions",],1000)

PenelopeSumReturn<-random.sample.times(Penelope[Penelope$GameName!="Pick 4" & Penelope$GameName!="Pick 3" & Penelope$GameName!="Wild 8s" & Penelope$GameName!="Powerball"& Penelope$GameName!="Cash 5"& Penelope$GameName!="Mega Millions" ,],1000)+pick4Alg(Penelope[Penelope$GameName=="Pick 4" | Penelope$GameName=="Pick 3" | Penelope$GameName=="Wild 8s",],1000) + MegaAlg(Penelope[Penelope$GameName=="Mega Millions",],1000) + PowerAlg(Penelope[Penelope$GameName=="Powerball",],1000) + Cash5Alg(Penelope[Penelope$GameName=="Cash 5",],1000)

Paul1SumReturn<-random.sample.times(Paul1[Paul1$GameName!="Pick 4" & Paul1$GameName!="Pick 3" & Paul1$GameName!="Wild 8s" & Paul1$GameName!="Mega Millions",],1000) + MegaAlg(Paul1[Paul1$GameName=="Mega Millions",],1000)

HubertSumReturn<-random.sample.times(Hubert[Hubert$GameName!="Pick 4" & Hubert$GameName!="Pick 3" & Hubert$GameName!="Wild 8s",],1000)

CharlesSumReturn<-random.sample.times(Charles[Charles$GameName!="Pick 4" & Charles$GameName!="Pick 3" & Charles$GameName!="Wild 8s",],1000)

KevanSumReturn<-random.sample.times(Kevan[Kevan$GameName!="Pick 4" & Kevan$GameName!="Pick 3" & Kevan$GameName!="Wild 8s",],1000)

EddieSumReturn<-random.sample.times(Eddie[Eddie$GameName!="Pick 4" & Eddie$GameName!="Pick 3" & Eddie$GameName!="Wild 8s",],1000)

James1SumReturn<-random.sample.times(James1[James1$GameName!="Pick 4" & James1$GameName!="Pick 3" & James1$GameName!="Wild 8s",],1000)

Paul2SumReturn<-random.sample.times(Paul2[Paul2$GameName!="Pick 4" & Paul2$GameName!="Pick 3" & Paul2$GameName!="Wild 8s",],1000)

BernadetteSumReturn<-random.sample.times(Bernadette[Bernadette$GameName!="Pick 4" & Bernadette$GameName!="Pick 3" & Bernadette$GameName!="Wild 8s",],1000)+pick4Alg(Bernadette[Bernadette$GameName=="Pick 4" | Bernadette$GameName=="Pick 3" | Bernadette$GameName=="Wild 8s",],1000)

HowardSumReturn<-random.sample.times(Howard[Howard$GameName!="Pick 4" & Howard$GameName!="Pick 3" & Howard$GameName!="Wild 8s",],1000)

LatishaSumReturn<-random.sample.times(Latisha[Latisha$GameName!="Pick 4" & Latisha$GameName!="Pick 3" & Latisha$GameName!="Wild 8s",],1000)+pick4Alg(Latisha[Latisha$GameName=="Pick 4" | Latisha$GameName=="Pick 3" | Latisha$GameName=="Wild 8s",],1000)

StevenSumReturn<-random.sample.times(Steven[Steven$GameName!="Pick 4" & Steven$GameName!="Pick 3" & Steven$GameName!="Wild 8s",],1000)

CuarlesSumReturn<-random.sample.times(Cuarles[Cuarles$GameName!="Pick 4" & Cuarles$GameName!="Pick 3" & Cuarles$GameName!="Wild 8s",],1000)+pick4Alg(Cuarles[Cuarles$GameName=="Pick 4" | Cuarles$GameName=="Pick 3" | Cuarles$GameName=="Wild 8s",],1000)
```
```
```
```{r create dataframe with simulation result}
cluster2SumReturn<-data_frame(Name=c("Winner 10","Winner 11","Winner 12","Winner 13","Winner 14","Winner 15","Winner 16","Winner 17","Winner 18","Winner 19","Winner 20","Winner 21","Winner 22","Winner 23"),"mean Instant"=c(mean(ReginaldSumReturn),mean(PenelopeSumReturn),mean(Paul1SumReturn),mean(HubertSumReturn),mean(CharlesSumReturn),mean(KevanSumReturn),mean(EddieSumReturn),mean(James1SumReturn),mean(Paul2SumReturn),mean(BernadetteSumReturn),mean(HowardSumReturn),mean(LatishaSumReturn),mean(StevenSumReturn),mean(CuarlesSumReturn)),"Minimum Cost Instant"=c(max(ReginaldSumReturn),max(PenelopeSumReturn),max(Paul1SumReturn),max(HubertSumReturn),max(CharlesSumReturn),max(KevanSumReturn),max(EddieSumReturn),max(James1SumReturn),max(Paul2SumReturn),max(BernadetteSumReturn),max(HowardSumReturn),max(LatishaSumReturn),max(StevenSumReturn),max(CuarlesSumReturn)),"Maximum Cost Instant"=c(min(ReginaldSumReturn),min(PenelopeSumReturn),min(Paul1SumReturn),min(HubertSumReturn),min(CharlesSumReturn),min(KevanSumReturn),min(EddieSumReturn),min(James1SumReturn),min(Paul2SumReturn),min(BernadetteSumReturn),min(HowardSumReturn),min(LatishaSumReturn),min(StevenSumReturn),min(CuarlesSumReturn)),"90% Percentile Instant"=c(quantile(ReginaldSumReturn,0.1),quantile(PenelopeSumReturn,0.1),quantile(Paul1SumReturn,0.1),quantile(HubertSumReturn,0.1),quantile(CharlesSumReturn,0.1),quantile(KevanSumReturn,0.1),quantile(EddieSumReturn,0.1),quantile(James1SumReturn,0.1),quantile(Paul2SumReturn,0.1),quantile(BernadetteSumReturn,0.1),quantile(HowardSumReturn,0.1),quantile(LatishaSumReturn,0.1),quantile(StevenSumReturn,0.1),quantile(CuarlesSumReturn,0.1)),"10% Percentile Instant"=c(quantile(ReginaldSumReturn,0.9),quantile(PenelopeSumReturn,0.9),quantile(Paul1SumReturn,0.9),quantile(HubertSumReturn,0.9),quantile(CharlesSumReturn,0.9),quantile(KevanSumReturn,0.9),quantile(EddieSumReturn,0.9),quantile(James1SumReturn,0.9),quantile(Paul2SumReturn,0.9),quantile(BernadetteSumReturn,0.9),quantile(HowardSumReturn,0.9),quantile(LatishaSumReturn,0.9),quantile(StevenSumReturn,0.9),quantile(CuarlesSumReturn,0.9)))

cluster2SumReturn<-cluster2SumReturn%>%rbind(topNineSumReturn)
```
```
```
```{r show the result}
cluster2SumReturn
```
