---
title: "Lottery_clearedCode"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```
```
```{r library}
library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(factoextra)
library(rlang)
```
```
```
```{r function}
#Function
random.sample <- function(x,y) {
  success <- FALSE
  result<-0
  time<-0
  while (!success) {
    i <- sample(x, 1,replace = T,prob = y)
    time=time+1
    if(i>=600){
      success<-TRUE
    }else{
      result=result+i
    }
  }
  return(c(time,result))
}
random.sample.times<-function(tempName,Time){
  sumReturn<-numeric(0)
  tempName$NumberToWin=0
  tempName$Won=0
  tempName$outPocket=0
  b<-0
  while(b < Time){
    for(a in 1:nrow(tempName)){
      if(tempName[a,]$Cost==2){
           temp<-random.sample(prize,lotteryProb[lotteryProb$Cost==2,-(1:2)])
           tempName[a,]$NumberToWin<-temp[1]
           tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$Cost==3){
           temp<-random.sample(prize,lotteryProb[lotteryProb$Cost==3,-(1:2)])
           tempName[a,]$NumberToWin<-temp[1]
           tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$Cost==5){
            temp<-random.sample(prize,lotteryProb[lotteryProb$Cost==5,-(1:2)])
            tempName[a,]$NumberToWin<-temp[1]
            tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$Cost==10){
             temp<-random.sample(prize,lotteryProb[lotteryProb$Cost==10,-(1:2)])
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$Cost==20){
             temp<-random.sample(prize,lotteryProb[lotteryProb$Cost==20,-(1:2)])
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$Cost==30){
             temp<-random.sample(prize,lotteryProb[lotteryProb$Cost==30,-(1:2)])
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }
    }
    tempName<-tempName%>%mutate(outPocket=NumberToWin*Cost-Won-PrizeAmount)
    sumReturn<-append(sumReturn,-sum(tempName$outPocket))
    b=b+1
}
  return(sumReturn)
}
pick4Alg<-function(tempName,Time){
  sumReturn<-numeric(0)
  tempName$NumberToWin=0
  tempName$Won=0
  tempName$outPocket=0
  b<-0
  while(b < Time){
    for(a in 1:nrow(tempName)){
      if(tempName[a,]$PrizeAmount==5000){
           temp<-random.sample(c(5000,0),c(1/10000,1-1/10000))
           tempName[a,]$NumberToWin<-temp[1]
           tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==1200){
           temp<-random.sample(c(1200,0),c(1/2500,1-1/2500))
           tempName[a,]$NumberToWin<-temp[1]
           tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==800){
            temp<-random.sample(c(800,0),c(6/10000,1-6/10000))
            tempName[a,]$NumberToWin<-temp[1]
            tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==3100|tempName[a,]$PrizeAmount==600){
             temp<-random.sample(c(3100,600,0),c(1/10000,3/10000,1-1/10000-3/10000))
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==2900){
             temp<-random.sample(c(2900,400,0),c(1/10000,5/10000,1-1/10000-5/10000))
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==2700){
             temp<-random.sample(c(2700,200,0),c(1/10000,11/10000,1-1/10000-11/10000))
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==2600){
             temp<-random.sample(c(2600,100,0),c(1/10000,23/10000,1-1/10000-23/10000))
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }else if(tempName[a,]$PrizeAmount==2500){
             temp<-random.sample(c(2500,0),c(1/10000,1-1/10000))/2
             tempName[a,]$NumberToWin<-temp[1]
             tempName[a,]$Won<-temp[2]
      }
    }
    tempName<-tempName%>%mutate(outPocket=NumberToWin*Cost-Won-PrizeAmount)
    sumReturn<-append(sumReturn,-sum(tempName$outPocket))
    b=b+1
}
  return(sumReturn)
}
```
```
```
```{r data_processing}
#README
#The simulation entropy datafram contains the log cost and entropy

#Read Data and add fullname
beforelottery<-read_xlsx("Single Claims 03.31.2006- 01.31.2020.xlsx")
beforelottery$Fullname<-paste(beforelottery$Claimant_FName,beforelottery$Claimant_MName,beforelottery$Claimant_LName)
```
```
```
```{r Curtis}
Curtis<-beforelottery[beforelottery$Fullname=="Curtis NA Richardson",]
#See Curtis
Curtis$ProbBigPrize<-0
Curtis$Cost<-0
Curtis$returnrate<-0
#Data for $1,000,000 BONUS CASH
Curtis[Curtis$GameName=="$1,000,000 BONUS CASH",][Curtis[Curtis$GameName=="$1,000,000 BONUS CASH",]$PrizeAmount==5000,]$ProbBigPrize=(4+50+125+2623)/6171541
Curtis[Curtis$GameName=="$1,000,000 BONUS CASH",][Curtis[Curtis$GameName=="$1,000,000 BONUS CASH",]$PrizeAmount==1000,]$ProbBigPrize=(4+50+125+2623)/6171541
Curtis[Curtis$GameName=="$1,000,000 BONUS CASH",]$Cost<-10
Curtis[Curtis$GameName=="$1,000,000 BONUS CASH",]$returnrate<-(500*5180+250*2462+150*2078+100*82397+50*67892+30*61808+20*452982+15*370634+10*700077)/(6171541*10)

#Can not find wild 8s

#HIT $5,000
Curtis[Curtis$GameName=="HIT $5,000",]$ProbBigPrize=(5+1260+280)/(1680000*5)
Curtis[Curtis$GameName=="HIT $5,000",]$Cost<-10
Curtis[Curtis$GameName=="HIT $5,000",]$returnrate<-(500*871+400*872+200*7198+100*45004+50*288377+40*144202+25*288377+20*288346+15*288377+10*865139)/(1680000*5*10)

#$1,000 MAYHEM
Curtis[Curtis$GameName=="$1,000 MAYHEM",]$ProbBigPrize=(4+15+8359)/7040995
Curtis[Curtis$GameName=="$1,000 MAYHEM",]$Cost<-10
Curtis[Curtis$GameName=="$1,000 MAYHEM",]$returnrate<-(500*590+100*93878+40*74520+30*58783+20*469566+15*469566+10*939132)/(7040995*10)

#$1,000,000 BACK SCRATCH
Curtis[Curtis$GameName=="$1,000,000 BACK SCRATCH",]$ProbBigPrize=(5+25+100+2500)/6000000
Curtis[Curtis$GameName=="$1,000,000 BACK SCRATCH",]$Cost<-10
Curtis[Curtis$GameName=="$1,000,000 BACK SCRATCH",]$returnrate<-(500*3854+250*3087+150*2079+100*82733+50*72010+30*61662+20*453064+15*370448+10*699919)/60000000

#$100,000 TAXES PAID
Curtis[Curtis$GameName=="$100,000 TAXES PAID",][Curtis[Curtis$GameName=="$100,000 TAXES PAID",]$PrizeAmount==1000,]$ProbBigPrize=(6+5+10+300)/6000000
Curtis[Curtis$GameName=="$100,000 TAXES PAID",]$Cost<-5
Curtis[Curtis$GameName=="$100,000 TAXES PAID",]$returnrate<-(500*800+50*34500+30*100000+20*100000+15*100000+10*500000+5*700000)/(6000000*5)#So small

#$150 MILLION CASH EXPLOSION
Curtis[Curtis$GameName=="$150 MILLION CASH EXPLOSION",]$ProbBigPrize=(4+6+10+150+283+5529)/11119810
Curtis[Curtis$GameName=="$150 MILLION CASH EXPLOSION",]$Cost<-20
Curtis[Curtis$GameName=="$150 MILLION CASH EXPLOSION",]$returnrate<-(500*22794+200*50959+100*302920+50*370705+40*370705+30*370705+25*741410+20*1482820)/(11119810*20)

#$2,500 FRENZY
Curtis[Curtis$GameName=="$2,500 FRENZY",][Curtis[Curtis$GameName=="$2,500 FRENZY",]$PrizeAmount==1000,]$ProbBigPrize=(4+8+2206+504)/7415655#1000 prize less than other price
Curtis[Curtis$GameName=="$2,500 FRENZY",]$Cost<-10
Curtis[Curtis$GameName=="$2,500 FRENZY",]$returnrate<-(500*736+400*744+200*6179+100*37116+50*247153+40*123455+25*247153+20*247212+15*247153+10*741827)/(7415655*10)


#$200 MILLION BLOWOUT
Curtis[Curtis$GameName=="$200 MILLION BLOWOUT",][Curtis[Curtis$GameName=="$200 MILLION BLOWOUT",]$PrizeAmount==1000,]$ProbBigPrize=(4+16+50+164+218+5401)/13451446
Curtis[Curtis$GameName=="$200 MILLION BLOWOUT",]$Cost<-20
Curtis[Curtis$GameName=="$200 MILLION BLOWOUT",]$returnrate<-(400*40420+200*22464+100*404203+50*404147+40*448979+30*897958+25*897958+20*1346937)/(13451446*20)

#$200 Million Extravaganza data missing

#$250,000 DIAMOND DAZZLER
Curtis[Curtis$GameName=="$250,000 DIAMOND DAZZLER",]$ProbBigPrize=(5+10+25+716)/5989620
Curtis[Curtis$GameName=="$250,000 DIAMOND DAZZLER",]$Cost<-5
Curtis[Curtis$GameName=="$250,000 DIAMOND DAZZLER",]$returnrate<-(500*770+150*1268+100*22302+50*49951+30*21485+25*46034+20*99878+15*59981+10*559281+5*599177)/(5989620*5)

#$250,000 PLATINUM PAYOUT
Curtis[Curtis$GameName=="$250,000 PLATINUM PAYOUT",]$ProbBigPrize=(6+8+14+945)/7400560
Curtis[Curtis$GameName=="$250,000 PLATINUM PAYOUT",]$Cost<-5
Curtis[Curtis$GameName=="$250,000 PLATINUM PAYOUT",]$returnrate<-(500*946+150*1579+100*25879+50*61626+30*39153+25*49394+20*123479+15*74089+10*691524+5*740786)/(7400560*5)

#$300,000,000 SUPREME RICHES
Curtis[Curtis$GameName=="$300,000,000 SUPREME RICHES",]$ProbBigPrize=(4+6+15+80+107+107+5533)/13214908
Curtis[Curtis$GameName=="$300,000,000 SUPREME RICHES",]$Cost<-30
Curtis[Curtis$GameName=="$300,000,000 SUPREME RICHES",]$returnrate<-(500*19876+400*77606+200*152633+100*334850+60*528887+50*1057410+40*1057523+30*1322228)/(13214908*30)

#$4,000,000 DIAMOND DAZZLER
Curtis[Curtis$GameName=="$4,000,000 DIAMOND DAZZLER",]$ProbBigPrize=(3+6+6+177+177+4086)/6889706
Curtis[Curtis$GameName=="$4,000,000 DIAMOND DAZZLER",]$Cost<-20
Curtis[Curtis$GameName=="$4,000,000 DIAMOND DAZZLER",]$returnrate<-(500*7504+200*6890+100*228304+50*229401+40*229415+30*229335+25*458830+20*917848)/(6889706*20)

#$4,000,000 MULTIPLIER SPECTACU	
Curtis[Curtis$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$ProbBigPrize=(4+10+25+190+302+388+6928)/10367589
Curtis[Curtis$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$Cost<-20
Curtis[Curtis$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$returnrate<-(14923*500+6872*400+34572*200+21564*150+276778*100+138572*50+233388*40+346006*30+1038018*25+1384024*20)/(10367589*20)

#$4,000,000 PLATINUM PAYOUT
Curtis[Curtis$GameName=="$4,000,000 PLATINUM PAYOUT",]$ProbBigPrize=(3+5+12+60+157+210+4611)/6921506
Curtis[Curtis$GameName=="$4,000,000 PLATINUM PAYOUT",]$Cost<-20
Curtis[Curtis$GameName=="$4,000,000 PLATINUM PAYOUT",]$returnrate<-(10056*500+4640*400+20752*200+191346*100+120881*50+172934*40+230713*30+691519*25+922480*20)/(6921506*20)

#	$5,000 LOADED
Curtis[Curtis$GameName=="$5,000 LOADED",]$ProbBigPrize=(4+928+239)/6992273
Curtis[Curtis$GameName=="$5,000 LOADED",]$Cost<-10
Curtis[Curtis$GameName=="$5,000 LOADED",]$returnrate<-(696*500+599*400+4242*200+46560*100+233176*50+174967*40+582770*20+699528*10)/(6992273*10)

#$5,000,000 FORTUNE
Curtis[Curtis$GameName=="$5,000,000 FORTUNE",]$ProbBigPrize=(3+6+158+180+3529)/7054163
Curtis[Curtis$GameName=="$5,000,000 FORTUNE",]$Cost<-20
Curtis[Curtis$GameName=="$5,000,000 FORTUNE",]$returnrate<-(5871*500+5833*300+236780*100+293484*50+234787*40+234787*30+469545*25+939148*20)/(7054163*20)

#$5,000,000 MEGA CASH
Curtis[Curtis$GameName=="$5,000,000 MEGA CASH",]$ProbBigPrize=(3+6+6+156+180+3751)/7050754
Curtis[Curtis$GameName=="$5,000,000 MEGA CASH",]$Cost<-20
Curtis[Curtis$GameName=="$5,000,000 MEGA CASH",]$returnrate<-(5896*500+5892*300+229087*100+234614*50+234781*40+234842*30+469562*25+939336*20)/(7050754*20)

#100X THE CASH
Curtis[Curtis$GameName=="100X THE CASH",]$ProbBigPrize=(4+6+50+185+308+1233)/7302532
Curtis[Curtis$GameName=="100X THE CASH",]$Cost<-20
Curtis[Curtis$GameName=="100X THE CASH",]$returnrate<-(7740*500+7200*200+239040*100+240000*120+480000*25+20*960000)/(2400000*3*20)

#	10x The Money
Curtis[Curtis$GameName=="10x The Money",]$ProbBigPrize=(8+27)/13822463
Curtis[Curtis$GameName=="10x The Money",]$Cost<-2
Curtis[Curtis$GameName=="10x The Money",]$returnrate<-(584*500+1387*200+17239*100+17263*50+33067*40+44261*30+69084*20+368411*10+5*184191+4*644631+2*1657751)/(13822463*2)

#10X THE PAYOUT missing data

#50X THE CASH
Curtis[Curtis$GameName=="50X THE CASH",]$ProbBigPrize=(6+8+20+162+1119)/6658607
Curtis[Curtis$GameName=="50X THE CASH",]$Cost<-10
Curtis[Curtis$GameName=="50X THE CASH",]$returnrate<-(3328*500+1697*250+2045*150+81967*100+44383*50+55363*40+66470*30+110796*25+20*443298+15*443298+10*664947)/(6658607*10)

#50X THE CASH!
Curtis[Curtis$GameName=="50X THE CASH!",]$ProbBigPrize=(6+8+20+162+1119)/6658607
Curtis[Curtis$GameName=="50X THE CASH!",]$Cost<-10
Curtis[Curtis$GameName=="50X THE CASH!",]$returnrate<-(3328*500+1697*250+2045*150+81967*100+44383*50+55363*40+66470*30+110796*25+20*443298+15*443298+10*664947)/(6658607*10)

#5X THE CASH!
Curtis[Curtis$GameName=="5X THE CASH!",]$ProbBigPrize=12/14207139# No 1000 prize
Curtis[Curtis$GameName=="5X THE CASH!",]$Cost<-1
Curtis[Curtis$GameName=="5X THE CASH!",]$returnrate<-(48*500+3850*100+11890*40+8214*30+47344*20+142032*10+5*142032+4*177539+2*1088895+1*1420358)/(14207139*1)

#	777
Curtis[Curtis$GameName=="777",]$ProbBigPrize=(4+4+8+719)/6167263# No 1000 prize
Curtis[Curtis$GameName=="777",]$Cost<-5
Curtis[Curtis$GameName=="777",]$returnrate<-(529*577+741*500+27703*100+15443*77+25227*50+205564*20+565254*10+308364*7+5*308440)/(6167263*5)

#BIG WIN
Curtis[Curtis$GameName=="BIG WIN",]$ProbBigPrize=(4+6+12+552)/(4*1380000)
Curtis[Curtis$GameName=="BIG WIN",]$Cost<-5
Curtis[Curtis$GameName=="BIG WIN",]$returnrate<-(1058*500+3036*200+23184*100+45540*50+161000*20+506000*10+5*552000)/(4*1380000*5)


#	BONUS JACKPOT missing data

#	CAROLINA BLACK
Curtis[Curtis$GameName=="CAROLINA BLACK",]$ProbBigPrize=(6+9+9+669)/(9823096)
Curtis[Curtis$GameName=="CAROLINA BLACK",]$Cost<-5
Curtis[Curtis$GameName=="CAROLINA BLACK",]$returnrate<-(1475*400+3680*200+24546*100+163627*50+327473*20+818445*10+5*982306)/(9823096*5)

#CAROLINA MILLIONS
Curtis[Curtis$GameName=="CAROLINA MILLIONS",]$ProbBigPrize=(8+12+48+240+1728)/(8*1080000)
Curtis[Curtis$GameName=="CAROLINA MILLIONS",]$Cost<-10
Curtis[Curtis$GameName=="CAROLINA MILLIONS",]$returnrate<-(4032*500+1296*250+115200*100+57600*50+70560*40+86400*30+115200*25+576000*35+864000*10)/(1080000*8*10)

#	CAROLINA PANTHERS
Curtis[Curtis$GameName=="CAROLINA PANTHERS",]$ProbBigPrize=(6+12+209)/(6138493)
Curtis[Curtis$GameName=="CAROLINA PANTHERS",]$Cost<-5
Curtis[Curtis$GameName=="CAROLINA PANTHERS",]$returnrate<-(782*400+10283*100+81961*50+33306*30+245818*20+532544*10+614508*5)/(6138493*5)


#Cash Spectacular missing data

#EXTREME MILLIONS
Curtis[Curtis$GameName=="EXTREME MILLIONS",]$ProbBigPrize=(4+22+40+16+301+15876)/(17651318)
Curtis[Curtis$GameName=="EXTREME MILLIONS",]$Cost<-30
Curtis[Curtis$GameName=="EXTREME MILLIONS",]$returnrate<-(58799*500+30817*300+70713*200+812201*100+705844*60+1293450*50+1529177*40+30*1764348)/(17651318*30)

#	GOLD
Curtis[Curtis$GameName=="GOLD",]$ProbBigPrize=(4+6+339)/(5081101)
Curtis[Curtis$GameName=="GOLD",]$Cost<-5
Curtis[Curtis$GameName=="GOLD",]$returnrate<-(695*400+1443*200+9747*100+63449*50+25346*25+253928*20+338393*10+5*507856)/(5081101*5)

#JUMBO BUCKS	
Curtis[Curtis$GameName=="JUMBO BUCKS",]$ProbBigPrize=(16+32+64+64+3276)/(15631549)
Curtis[Curtis$GameName=="JUMBO BUCKS",]$Cost<-10
Curtis[Curtis$GameName=="JUMBO BUCKS",]$returnrate<-(7841*500+109758*100+253098*50+626125*25+1043624*20+1043187*15+10*1056162)/(15631549*10)


#	MILLIONAIRE 7S 
Curtis[Curtis$GameName=="MILLIONAIRE 7S",]$ProbBigPrize=(10+8+100+2004)/9875096
Curtis[Curtis$GameName=="MILLIONAIRE 7S",]$Cost<-10
Curtis[Curtis$GameName=="MILLIONAIRE 7S",]$returnrate<-(8080*500+6930*200+100*135107+82282*40+280134*25+659086*20+659086*15+10*988629)/(9875096*10)

# THE BIG $5 TICKET
Curtis[Curtis$GameName=="THE BIG $5 TICKET",]$ProbBigPrize=(4+6+12+300)/4800000
Curtis[Curtis$GameName=="THE BIG $5 TICKET",]$Cost<-5
Curtis[Curtis$GameName=="THE BIG $5 TICKET",]$returnrate<-(500*960+200*4000+100*18400+50*36440+20*140000+10*440000+5*480000)/(5*4800000)

# RED HOT MILLION$
Curtis[Curtis$GameName=="RED HOT MILLION$",]$ProbBigPrize=(4+30+103+1055)/6243901
Curtis[Curtis$GameName=="RED HOT MILLION$",]$Cost<-10
Curtis[Curtis$GameName=="RED HOT MILLION$",]$returnrate<-(2638*500+3129*200+100*82082+59700*50+97034*30+624006*20+415942*15+10*623727)/(6243901*10)

# TREASURE HUNT
Curtis[Curtis$GameName=="TREASURE HUNT",]$ProbBigPrize=(6+360+103+1055)/(6*720000)
Curtis[Curtis$GameName=="TREASURE HUNT",]$Cost<-3
Curtis[Curtis$GameName=="TREASURE HUNT",]$returnrate<-(500*540+100*5580+50*22068+20*43200+15*51840+10*129600+5*345600+3*432000)/(6*720000*3)

#	SPOOKY BUCKS
Curtis[Curtis$GameName=="SPOOKY BUCKS",]$ProbBigPrize=(4+30+96)/(4*960000)
Curtis[Curtis$GameName=="SPOOKY BUCKS",]$Cost<-3
Curtis[Curtis$GameName=="SPOOKY BUCKS",]$returnrate<-(500*160+100*7488+50*13440+40*3200+30*8000+20*61440+10*138240+5*345600+3*384000)/(4*960000*3)

#	ULTIMATE MILLIONS
Curtis[Curtis$GameName=="ULTIMATE MILLIONS",]$ProbBigPrize=(4+18+20+32+720+14364)/(4*3990000)
Curtis[Curtis$GameName=="ULTIMATE MILLIONS",]$Cost<-30
Curtis[Curtis$GameName=="ULTIMATE MILLIONS",]$returnrate<-(500*53200+300*27930+200*63840+100*718200+60*638400+1170400*50+1383200*40+1596000*30)/(4*3990000*30)

#	RUBY RED 7S
Curtis[Curtis$GameName=="RUBY RED 7S",]$ProbBigPrize=(3+4+8+105+390+2520)/(3*1800000)
Curtis[Curtis$GameName=="RUBY RED 7S",]$Cost<-20
Curtis[Curtis$GameName=="RUBY RED 7S",]$returnrate<-(500*8100+400*2790+200*18000+100*152100+50*72000+139500*40+180000*30+540000*25+720000*20)/(3*1800000*20)

# $4,000,000 MULTIPLIER SPECTACU
Curtis[Curtis$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$ProbBigPrize=(4+10+25+190+294+378+6720)/(4*2520000)
Curtis[Curtis$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$Cost<-20
Curtis[Curtis$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$returnrate<-(500*14448+400*6719+200*33600+150*21000+268800*100+134400*50+226800*40+336000*30+1008000*25+1344000*20)/(4*2520000*20)

#	GOLDEN 7s
Curtis[Curtis$GameName=="GOLDEN 7s",]$ProbBigPrize=(5+6+170)/(5*816000)
Curtis[Curtis$GameName=="GOLDEN 7s",]$Cost<-5
Curtis[Curtis$GameName=="GOLDEN 7s",]$returnrate<-(544*200+11220*100+44608*40+68000*25+136000*20+340000*10+476000*5)/(5*816000*5)

# BONUS JACKPOT
Curtis[Curtis$GameName=="BONUS JACKPOT",]$ProbBigPrize=(4+20+110)/(4*990000)
Curtis[Curtis$GameName=="BONUS JACKPOT",]$Cost<-5
Curtis[Curtis$GameName=="BONUS JACKPOT",]$returnrate<-(1518*250+7722*100+50820*50+66000*25+99000*20+297000*10+462000*5)/(4*990000*5)

#10X THE PAYOUT
Curtis[Curtis$GameName=="10X THE PAYOUT",]$ProbBigPrize=(6+15+301)/(6*860000)
Curtis[Curtis$GameName=="10X THE PAYOUT",]$Cost<-5
Curtis[Curtis$GameName=="10X THE PAYOUT",]$returnrate<-(645*500+13760*100+61060*50+86000*30+107500*20+344000*10+688000*5)/(6*860000*5)

#$200 Million Extravaganza
Curtis[Curtis$GameName=="$200 Million Extravaganza",]$ProbBigPrize=(5+10+10+224+672+11760)/(5*2688000)
Curtis[Curtis$GameName=="$200 Million Extravaganza",]$Cost<-20
Curtis[Curtis$GameName=="$200 Million Extravaganza",]$returnrate<-(17920*500+53760*200+266000*100+246400*50+896000*30+1792000*25+1792000*20)/(5*2688000*20)

# Cash Spectacular	
Curtis[Curtis$GameName=="Cash Spectacular",]$ProbBigPrize=(10+20+146+292+5840)/(10*1752000)
Curtis[Curtis$GameName=="Cash Spectacular",]$Cost<-10
Curtis[Curtis$GameName=="Cash Spectacular",]$returnrate<-(14600*500+182500*100+204400*50+233600*25+1752000*20+1168000*15+1752000*10)/(10*1752000*10)

#See the calculation based on now data 
Curtisdata<-Curtis[Curtis$Cost!=0&Curtis$returnrate!=0,]
(1-0.5120512)*qgamma(0.05,277,mean(Curtisdata$ProbBigPrize))-sum(Curtis$PrizeAmount)
#moneyindividual(nrow(Curtisdata),0.05,mean(Curtisdata$ProbBigPrize))*(1-mean(Curtisdata$returnrate))-sum(Curtisdata$PrizeAmount)
#Lost -3354336 not so much
#The main problem may be in Pick4
#Adding Pick4 now -573121.8

#Pick 3
#for Pick 3 the prize is only 500 this means he is both the winner of daytime and evening???
Curtis[Curtis$GameName=="Pick 3",]$ProbBigPrize=1/(1000)
Curtis[Curtis$GameName=="Pick 3",]$Cost<-1
Curtis[Curtis$GameName=="Pick 3",]$returnrate<-(500+160+80+330+80+290+40+500+500+100+40+10+18)/(1000+333.3+166.7+1000+333.3+1000+166.7+333.3*3+166.7*6+200+166.67+83.33+125)
#Do not know the payout rate no data about how many people buy it

#Pick 4
Curtis[Curtis$GameName=="Pick 4",]$ProbBigPrize=5/(10000)+3/2500+2/1666.7+1/833.3+1/416.7
Curtis[Curtis$GameName=="Pick 4",]$Cost<-1
Curtis[Curtis$GameName=="Pick 4",]$returnrate<-(5000+1200+800+400+200+3100+600+2900+400+2700+200+2600+100+5000*4+100+300+40+26+52)/(10000+2500+1666.7+833.3+416.7+10000+2500+10000+1666.7+10000+10000+833.3+416.7+10000+6*1666.7+12*833.3+416.7*24+100+100+1250+416/67+312.5+625)

#	Wild 8s Note: these are missing data but from the prize, it is quite likely this is pick 4 so we suppose it is pick4
Curtis[Curtis$GameName=="Wild 8s",]$ProbBigPrize=5/(10000)+3/2500+2/1666.7+1/833.3+1/416.7
Curtis[Curtis$GameName=="Wild 8s",]$Cost<-1
Curtis[Curtis$GameName=="Wild 8s",]$returnrate<-(5000+1200+800+400+200+3100+600+2900+400+2700+200+2600+100+5000*4+100+300+40+26+52)/(10000+2500+1666.7+833.3+416.7+10000+2500+10000+1666.7+10000+10000+833.3+416.7+10000+6*1666.7+12*833.3+416.7*24+100+100+1250+416/67+312.5+625)

```
```
```
```{r entropy and log cost}
#Calculate the entropy for all people
allPeople_onlycount<-beforelottery%>%group_by(Fullname)%>%summarise(count=n())
allPeople_unfiltered<-beforelottery%>%right_join(allPeople_onlycount,by="Fullname")
allPeople<-allPeople_unfiltered[is.na(allPeople_unfiltered$count)==FALSE,]
allPeople_store_count<-allPeople%>%group_by(Fullname,SellingRetailerName)%>%summarise(count=n())
allPeople<-allPeople%>%left_join(allPeople_store_count,by=c("Fullname","SellingRetailerName"))
allPeople_select<-allPeople%>%select(Fullname,SellingRetailerName,count.x,count.y)%>%rename("WinningCount"=count.x,"StoreCount"=count.y)
allPeople_select<-allPeople_select%>%unique()%>%mutate(possibility=StoreCount/(WinningCount))
allPeople_select<-allPeople_select%>%group_by(Fullname)%>%mutate(entropy=-sum(possibility*log(possibility)))
#All people select is the processed data for entropy

#Calculate the expected out of pocket
beforelottery_simulation<-beforelottery%>%mutate("Estimated money"= 1/0.001226816)
beforelottery_simulation<-beforelottery_simulation%>%group_by(Fullname)%>%mutate("Estimate total money"=sum(`Estimated money`)*14.32653*(1-0.6050788)-sum(PrizeAmount))
beforelottery_simulation<-beforelottery_simulation%>%mutate("Log Cost"=log10(max(1,`Estimate total money`,na.rm = T)))
beforelottery_simulation_selected<-beforelottery_simulation%>%select(Fullname,`Estimated money`,`Estimate total money`)%>%unique()%>%mutate("Log Cost"=log10(max(1,`Estimate total money`,na.rm = T)))

#Combine together
simulation_entropy<-beforelottery_simulation_selected%>%full_join(allPeople_select,by="Fullname")

#Graph
simulation_entropy%>%ggplot(aes(x=entropy,y=`Log Cost`))+geom_point()+ggtitle("Log Cost vs Entropy")+xlab("Entropy")+ylab("Log Cost")
```
```
```
```{r top Nine}
simulation_entropy_unique<-simulation_entropy[!duplicated(simulation_entropy$Fullname),]
topNine<- simulation_entropy_unique[order(simulation_entropy_unique$entropy+simulation_entropy_unique$`Log Cost`,decreasing = T),]%>%head(9)
```
```
```
```{r lottery information}
prize<-c(10000000,4000000,1000000,250000,100000,50000,20000,10000,5000,4000,2500,2000,1000,500,400,300,200,150,100,60,50,40,30,25,20,15,10,5,4,3,2,0)
lotteryProb<-data_frame(Gamename=c("10x The Money","TREASURE HUNT","$250,000 PLATINUM PAYOUT","$2,500 FRENZY","$4,000,000 PLATINUM PAYOUT","ULTIMATE MILLIONS"),Cost=c(2,3,5,10,20,30))

#Make all the probability equal to 0 as default
lotteryProb$tenmillion<-0
lotteryProb$fourmillion<-0
lotteryProb$onemillion<-0
lotteryProb$twohundredfiftythousand<-0
lotteryProb$onehundredthousand<-0
lotteryProb$fiftythousand<-0
lotteryProb$twentythousand<-0
lotteryProb$tenthousand<-0
lotteryProb$fivethousand<-0
lotteryProb$fourthousand<-0
lotteryProb$twothousandfivehundred<-0
lotteryProb$twothousand<-0
lotteryProb$onethousand<-0
lotteryProb$fivehundred<-0
lotteryProb$fourhundred<-0
lotteryProb$threehundred<-0
lotteryProb$twohundred<-0
lotteryProb$onehundredfifty<-0
lotteryProb$onehundred<-0
lotteryProb$sixty<-0
lotteryProb$fifty<-0
lotteryProb$forty<-0
lotteryProb$thirty<-0
lotteryProb$twentyfive<-0
lotteryProb$twenty<-0
lotteryProb$fifteen<-0
lotteryProb$ten<-0
lotteryProb$five<-0
lotteryProb$four<-0
lotteryProb$three<-0
lotteryProb$two<-0
lotteryProb$zero<-0
#First see 10x The Money
lotteryProb[lotteryProb$Gamename=="10x The Money",]$onehundredthousand=6/((6+150+261+6376+53271+82369+164738+329547+658810)*3.81)
lotteryProb[lotteryProb$Gamename=="10x The Money",]$onethousand=150/((6+150+261+6376+53271+82369+164738+329547+658810)*3.81)
lotteryProb[lotteryProb$Gamename=="10x The Money",]$fivehundred=261/((6+150+261+6376+53271+82369+164738+329547+658810)*3.81)
lotteryProb[lotteryProb$Gamename=="10x The Money",]$onehundred=6376/((6+150+261+6376+53271+82369+164738+329547+658810)*3.81)
lotteryProb[lotteryProb$Gamename=="10x The Money",]$fifty=53271/((6+150+261+6376+53271+82369+164738+329547+658810)*3.81)
lotteryProb[lotteryProb$Gamename=="10x The Money",]$thirty=82369/((6+150+261+6376+53271+82369+164738+329547+658810)*3.81)
lotteryProb[lotteryProb$Gamename=="10x The Money",]$twenty=164738/((6+150+261+6376+53271+82369+164738+329547+658810)*3.81)
lotteryProb[lotteryProb$Gamename=="10x The Money",]$ten=329547/((6+150+261+6376+53271+82369+164738+329547+658810)*3.81)
lotteryProb[lotteryProb$Gamename=="10x The Money",]$five=658810/((6+150+261+6376+53271+82369+164738+329547+658810)*3.81)
lotteryProb[lotteryProb$Gamename=="10x The Money",]$zero=1-sum(lotteryProb[lotteryProb$Gamename=="10x The Money",3:33])
#TREASURE HUNT
lotteryProb[lotteryProb$Gamename=="TREASURE HUNT",]$fiftythousand=6/4371276
lotteryProb[lotteryProb$Gamename=="TREASURE HUNT",]$onethousand=369/4371276
lotteryProb[lotteryProb$Gamename=="TREASURE HUNT",]$fivehundred=556/4371276
lotteryProb[lotteryProb$Gamename=="TREASURE HUNT",]$onehundred=5637/4371276
lotteryProb[lotteryProb$Gamename=="TREASURE HUNT",]$fifty=22335/4371276
lotteryProb[lotteryProb$Gamename=="TREASURE HUNT",]$twenty=43721/4371276
lotteryProb[lotteryProb$Gamename=="TREASURE HUNT",]$fifteen=52469/4371276
lotteryProb[lotteryProb$Gamename=="TREASURE HUNT",]$ten=131114/4371276
lotteryProb[lotteryProb$Gamename=="TREASURE HUNT",]$five=349866/4371276
lotteryProb[lotteryProb$Gamename=="TREASURE HUNT",]$three=437191/4371276
lotteryProb[lotteryProb$Gamename=="TREASURE HUNT",]$zero=1-sum(lotteryProb[lotteryProb$Gamename=="TREASURE HUNT",3:33])
#$250,000 PLATINUM PAYOUT
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$twohundredfiftythousand =6/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$tenthousand =8/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$twothousand =14/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$onethousand =945/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$fivehundred=946/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$onehundredfifty =1579/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$onehundred=25879/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$fifty=61626/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$thirty=39153/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$twentyfive =49394/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$twenty=123479/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$fifteen =74089/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$ten=691524/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$five=740786/7400560
lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",]$zero=1-sum(lotteryProb[lotteryProb$Gamename=="$250,000 PLATINUM PAYOUT",3:33])
#$2,500 FRENZY
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$onemillion =4/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$tenthousand =8/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$twothousandfivehundred =2206/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$onethousand =504/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$fivehundred=736/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$fourhundred =744/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$twohundred =6179/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$onehundred=37116/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$fifty=247153/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$forty =123455/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$twentyfive =247153/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$twenty=247212/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$fifteen =247153/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$ten=741827/7415655
lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",]$zero=1-sum(lotteryProb[lotteryProb$Gamename=="$2,500 FRENZY",3:33])
#$4,000,000 PLATINUM PAYOUT
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$fourmillion =3/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$onemillion =5/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$onehundredthousand =12/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$tenthousand =60/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$fourthousand =157/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$twothousand =210/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$onethousand =4611/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$fivehundred=10056/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$fourhundred =4640/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$twohundred =20752/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$onehundred=191346/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$fifty=120881/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$forty =172934/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$thirty =230713/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$twentyfive =691519/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$twenty=922480/6921506
lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",]$zero=1-sum(lotteryProb[lotteryProb$Gamename=="$4,000,000 PLATINUM PAYOUT",3:33])
#ULTIMATE MILLIONS
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$tenmillion =4/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$onemillion =18/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$fiftythousand =20/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$twentythousand =32/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$fourthousand =720/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$onethousand =14364/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$fivehundred=53200/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$threehundred =27930/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$twohundred =63840/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$onehundred=718200/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$sixty=638400/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$fifty=1170400/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$forty =1383200/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$thirty =1596000/(4*3990000)
lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",]$zero=1-sum(lotteryProb[lotteryProb$Gamename=="ULTIMATE MILLIONS",3:33])
```
```
```
```{r Pick 4&Pick 3}
prizePick4<-c(5000,3100,2900,2700,2600,1200,800,600,400,300,200,100,52,50,40,26,0)
Pick4Prob<-data_frame(Gamename=c("Pick 4"),Cost = 1)
Pick4Prob$fivethousand<-1/10000
Pick4Prob$threethousandonehundred<-1/10000
Pick4Prob$twothousandninehundred<-1/10000
Pick4Prob$twothousandsevenhundred<-1/10000
Pick4Prob$twothousandsixhundred<-1/10000
Pick4Prob$onethousandtwohundered<-1/2500
Pick4Prob$eighthundred<-1/1666.7
Pick4Prob$sixhundred<-1/2500
Pick4Prob$fourhundred<-1/833.3+1/1666.7
Pick4Prob$threehundred<-1/1250
Pick4Prob$twohundred<-1/833.3+1/416.7
Pick4Prob$onehundred<-1/416.7
Pick4Prob$fiftytwo<-1/625
Pick4Prob$fifty<-1/100+1/100
Pick4Prob$forty<-1/416.67
Pick4Prob$twentysix<-1/312.5
Pick4Prob$zero<-1-(1/10000*5+1/2500+1/1666.7+1/2500+1/833.3+1/1666.7+1/1250+1/833.3+1/416.7+1/416.7+1/625+1/100+1/100+1/416.67+1/312.5)

Pick3Prob<-data_frame(Gamename=c("Pick 3"),Prize=c(1000,500,160,80,330,80,290,40,500,500,50,50,40,10,18,0),Prob=c(91*(1/1000)^2*(999/1000)^12,1/1000,1/333.3,1/166.7,1/1000,1/333.3,1/1000,1/166.7,1/1/333.3,1/166.7,1/100,1/100,1/166.67,1/83.33,1/125,1-(91*(1/1000)^2*(999/1000)^12+1/1000+1/333.3+1/166.7+1/1000+1/333.3+1/1000+1/166.7+1/1/333.3+1/166.7+1/100+1/100+1/166.67+1/83.33+1/125)))
```
```
```
```{r James}
#James Randall Bray
James<-beforelottery[beforelottery$Fullname=="James Randall Bray",]
James$ProbBigPrize=0
James$returnrate=0
James$Cost=0

#ULTIMATE MILLIONS
James[James$GameName=="ULTIMATE MILLIONS",]$ProbBigPrize=(4+18+20+32+720+14364)/(4*3990000)
James[James$GameName=="ULTIMATE MILLIONS",]$Cost<-30
James[James$GameName=="ULTIMATE MILLIONS",]$returnrate<-(500*53200+300*27930+200*63840+100*718200+60*638400+1170400*50+1383200*40+1596000*30)/(4*3990000*30)

#	THE COLOR OF MONEY
James[James$GameName=="THE COLOR OF MONEY",]$ProbBigPrize=(5+14+90+1200)/(5*1152000)
James[James$GameName=="THE COLOR OF MONEY",]$Cost<-10
James[James$GameName=="THE COLOR OF MONEY",]$returnrate<-(500*1920+200*2880+100*81600+50*40800+48000*40+52800*30+96000*25+20*384000+15*384000+10*576000)/(5*1152000*10)

#$120 MILLION CASH
James[James$GameName=="$120 MILLION CASH",]$ProbBigPrize=(4+6+6+198+198+5148)/(4*1980000)
James[James$GameName=="$120 MILLION CASH",]$Cost<-20
James[James$GameName=="$120 MILLION CASHY",]$returnrate<-(500*12144+200*40260+100*241560+50*158400+158400*40+264000*30+792000*25+20*1056000)/(4*1980000*10)

#$4,000,000 MULTIPLIER SPECTACU	
James[James$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$ProbBigPrize=(4+10+25+190+302+388+6928)/10367589
James[James$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$Cost<-20
James[James$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$returnrate<-(14923*500+6872*400+34572*200+21564*150+276778*100+138572*50+233388*40+346006*30+1038018*25+1384024*20)/(10367589*20)

#JUMBO BUCKS	
James[James$GameName=="JUMBO BUCKS",]$ProbBigPrize=(16+32+64+64+3276)/(15631549)
James[James$GameName=="JUMBO BUCKS",]$Cost<-10
James[James$GameName=="JUMBO BUCKS",]$returnrate<-(7841*500+109758*100+253098*50+626125*25+1043624*20+1043187*15+10*1056162)/(15631549*10)

#$200 MILLION BLOWOUT
James[James$GameName=="$200 MILLION BLOWOUT",][James[James$GameName=="$200 MILLION BLOWOUT",]$PrizeAmount==1000,]$ProbBigPrize=(4+16+50+164+218+5401)/13451446
James[James$GameName=="$200 MILLION BLOWOUT",]$Cost<-20
James[James$GameName=="$200 MILLION BLOWOUT",]$returnrate<-(400*40420+200*22464+100*404203+50*404147+40*448979+30*897958+25*897958+20*1346937)/(13451446*20)

#$200 Million Extravaganza
James[James$GameName=="$200 Million Extravaganza",]$ProbBigPrize=(5+10+10+224+672+11760)/(5*2688000)
James[James$GameName=="$200 Million Extravaganza",]$Cost<-20
James[James$GameName=="$200 Million Extravaganza",]$returnrate<-(17920*500+53760*200+266000*100+246400*50+896000*30+1792000*25+1792000*20)/(5*2688000*20)

#$200,000 A Year For Life
James[James$GameName=="$200,000 A Year For Life",]$ProbBigPrize=(3+7+140+140+2777)/((3+7+140+140+2777+19001+275880+181046+137920+275980+827940+1103920)*2.93)
James[James$GameName=="$200,000 A Year For Life",]$Cost<-20
James[James$GameName=="$200,000 A Year For Life",]$returnrate<-(19001*500+275880*100+181046*50+137920*40+275980*30+827940*25+1103920*20)/(((3+7+140+140+2777+19001+275880+181046+137920+275980+827940+1103920)*2.93)*20)

#Cash Bonanza
James[James$GameName=="Cash Bonanza",]$ProbBigPrize=(4+5+10+26)/(4*780000)
James[James$GameName=="Cash Bonanza",]$Cost<-5
James[James$GameName=="Cash Bonanza",]$returnrate<-(50*500+11310*100+41600*50+52000*25+52000*20+208000*10+416000*5)/(4*780000*5)

#$100,000 Treasure Tree
James[James$GameName=="$100,000 Treasure Tree",]$ProbBigPrize=(5+50)/((5+50+576+6605+46133+57649+115298+230596+461192)*3.77)
James[James$GameName=="$100,000 Treasure Tree",]$Cost<-5
James[James$GameName=="$100,000 Treasure Tree",]$returnrate<-(576*500+6605*100+46133*50+57649*25+115298*15+230596*10+5*461192)/(((5+50+576+6605+46133+57649+115298+230596+461192)*3.77)*5)

#	RUBY RED 7S
James[James$GameName=="RUBY RED 7S",]$ProbBigPrize=(3+4+8+105+390+2520)/(3*1800000)
James[James$GameName=="RUBY RED 7S",]$Cost<-20
James[James$GameName=="RUBY RED 7S",]$returnrate<-(500*8100+400*2790+200*18000+100*152100+50*72000+139500*40+180000*30+540000*25+720000*20)/(3*1800000*20)

#RUBY RED 7s
James[James$GameName=="RUBY RED 7s",]$ProbBigPrize=(3+4+8+105+390+2520)/(3*1800000)
James[James$GameName=="RUBY RED 7s",]$Cost<-20
James[James$GameName=="RUBY RED 7s",]$returnrate<-(500*8100+400*2790+200*18000+100*152100+50*72000+139500*40+180000*30+540000*25+720000*20)/(3*1800000*20)


#$5,000 A WEEK FOR LIFE!
James[James$GameName=="$5,000 A WEEK FOR LIFE!",]$ProbBigPrize=(3+100+253+3110)/((3+100+253+3110+4656+9235+153376+56594+66958+247210+823876+923839+1400613)*3.44)
James[James$GameName=="$5,000 A WEEK FOR LIFE!",]$Cost<-10
James[James$GameName=="$5,000 A WEEK FOR LIFE!",]$returnrate<-(4656*400+9235*200+153376*100+56594*50+66958*40+247210*25+823876*20+923839*15+1400613*10)/(((3+100+253+3110+4656+9235+153376+56594+66958+247210+823876+923839+1400613)*3.44)*10)

#100X THE CASH
James[James$GameName=="100X THE CASH",]$ProbBigPrize=(4+6+50+185+308+1233)/7302532
James[James$GameName=="100X THE CASH",]$Cost<-20
James[James$GameName=="100X THE CASH",]$returnrate<-(7740*500+7200*200+239040*100+240000*120+480000*25+20*960000)/(2400000*3*20)

#$4,000,000 PLATINUM PAYOUT
James[James$GameName=="$4,000,000 PLATINUM PAYOUT",]$ProbBigPrize=(3+5+12+60+157+210+4611)/6921506
James[James$GameName=="$4,000,000 PLATINUM PAYOUT",]$Cost<-20
James[James$GameName=="$4,000,000 PLATINUM PAYOUT",]$returnrate<-(10056*500+4640*400+20752*200+191346*100+120881*50+172934*40+230713*30+691519*25+922480*20)/(6921506*20)

#EXTREME MILLIONS
James[James$GameName=="EXTREME MILLIONS",]$ProbBigPrize=(4+22+40+16+301+15876)/(17651318)
James[James$GameName=="EXTREME MILLIONS",]$Cost<-30
James[James$GameName=="EXTREME MILLIONS",]$returnrate<-(58799*500+30817*300+70713*200+812201*100+705844*60+1293450*50+1529177*40+30*1764348)/(17651318*30)

#	$5,000 LOADED
James[James$GameName=="$5,000 LOADED",]$ProbBigPrize=(4+928+239)/6992273
James[James$GameName=="$5,000 LOADED",]$Cost<-10
James[James$GameName=="$5,000 LOADED",]$returnrate<-(696*500+599*400+4242*200+46560*100+233176*50+174967*40+582770*20+699528*10)/(6992273*10)

#$4,000,000 DIAMOND DAZZLER
James[James$GameName=="$4,000,000 DIAMOND DAZZLER",]$ProbBigPrize=(3+6+6+177+177+4086)/6889706
James[James$GameName=="$4,000,000 DIAMOND DAZZLER",]$Cost<-20
James[James$GameName=="$4,000,000 DIAMOND DAZZLER",]$returnrate<-(500*7504+200*6890+100*228304+50*229401+40*229415+30*229335+25*458830+20*917848)/(6889706*20)

#$5,000,000 MEGA CASH
James[James$GameName=="$5,000,000 MEGA CASH",]$ProbBigPrize=(3+6+6+156+180+3751)/7050754
James[James$GameName=="$5,000,000 MEGA CASH",]$Cost<-20
James[James$GameName=="$5,000,000 MEGA CASH",]$returnrate<-(5896*500+5892*300+229087*100+234614*50+234781*40+234842*30+469562*25+939336*20)/(7050754*20)

#CAROLINA MILLIONS
James[James$GameName=="CAROLINA MILLIONS",]$ProbBigPrize=(8+12+48+240+1728)/(8*1080000)
James[James$GameName=="CAROLINA MILLIONS",]$Cost<-10
James[James$GameName=="CAROLINA MILLIONS",]$returnrate<-(4032*500+1296*250+115200*100+57600*50+70560*40+86400*30+115200*25+576000*35+864000*10)/(1080000*8*10)

#$150 MILLION CASH EXPLOSION
James[James$GameName=="$150 MILLION CASH EXPLOSION",]$ProbBigPrize=(4+6+10+150+283+5529)/11119810
James[James$GameName=="$150 MILLION CASH EXPLOSION",]$Cost<-20
James[James$GameName=="$150 MILLION CASH EXPLOSION",]$returnrate<-(500*22794+200*50959+100*302920+50*370705+40*370705+30*370705+25*741410+20*1482820)/(11119810*20)

#$10,000,000 COLOSSAL CASH
James[James$GameName=="$10,000,000 COLOSSAL CASH",]$ProbBigPrize=(4+16+20+40+280+16500)/(3960000*4)
James[James$GameName=="$10,000,000 COLOSSAL CASH",]$Cost<-30
James[James$GameName=="$10,000,000 COLOSSAL CASH",]$returnrate<-(500*58080+300*36960+200*52800+100*688512+60*633600+50*1161600+40*1372800+30*1584000)/(3960000*4*30)

#$10,000 LOADED
James[James$GameName=="$10,000 LOADED",]$ProbBigPrize=(3+3+820+123)/(3*1640000)
James[James$GameName=="$10,000 LOADED",]$Cost<-20
James[James$GameName=="$10,000 LOADED",]$returnrate<-(500*2296+400*369+200*2542+100*123000+50*205000+40*205000+30*410000+20*656000)/(3*1640000*20)


#MILLION DOLLAR FEVER
James[James$GameName=="MILLION DOLLAR FEVER",]$ProbBigPrize=(5+75+95+1320)/(5*1320000)
James[James$GameName=="MILLION DOLLAR FEVER",]$Cost<-10
James[James$GameName=="MILLION DOLLAR FEVER",]$returnrate<-(500*2750+250*3300+100*86845+50*56375+40*55000+20*660000+15*440000+10*660000)/(5*1320000*10)

#SILVER & GOLD CROSSWORD
James[James$GameName=="SILVER & GOLD CROSSWORD",]$ProbBigPrize=(4+120+200)/(4*1200000)
James[James$GameName=="SILVER & GOLD CROSSWORD",]$Cost<-5
James[James$GameName=="SILVER & GOLD CROSSWORD",]$returnrate<-(500*800+300*600+200*800+100*14760+50*15000+40*40000+25*96000+20*80000+10*400000+5*560000)/(4*1200000*5)

#MILLIONAIRE BUCKS
James[James$GameName=="MILLIONAIRE BUCKS",]$ProbBigPrize=(4+6+50+80+120+450)/(4*1350000)
James[James$GameName=="MILLIONAIRE BUCKS",]$Cost<-20
James[James$GameName=="MILLIONAIRE BUCKS",]$returnrate<-(500*2970+200*36000+150*13500+100*144000+50*126000+40*180000+30*540000+20*720000)/(4*1350000*20)

#LUCKY NO. 7
James[James$GameName=="LUCKY NO. 7",]$ProbBigPrize=(6+96+96+1440)/(6*1200000)
James[James$GameName=="LUCKY NO. 7",]$Cost<-10
James[James$GameName=="LUCKY NO. 7",]$returnrate<-(500*2880+250*3600+100*95580+50*24000+25*153000+20*720000+15*480000+10*720000)/(6*1200000*10)

#$1,000,000 TAXES PAID
James[James$GameName=="$1,000,000 TAXES PAID",]$ProbBigPrize=(4+50+60+900)/(4*1800000)
James[James$GameName=="$1,000,000 TAXES PAID",]$Cost<-10
James[James$GameName=="$1,000,000 TAXES PAID",]$returnrate<-(500*2880+250*3000+100*96000+50*36000+40*60000+20*720000+15*480000+10*720000)/(4*1800000*10)
```
```
```
```{r Tawfik}
#Tawfik Mohammad Sharafi
Tawfik<-beforelottery[beforelottery$Fullname=="Tawfik Mohammad Sharafi",]
Tawfik$Cost<-0
Tawfik[Tawfik$GameName=="$1,000 MAYHEM",]$Cost<-10
Tawfik[Tawfik$GameName=="$1,000,000 BONUS CASH",]$Cost<-10
Tawfik[Tawfik$GameName=="$10,000,000 COLOSSAL CASH",]$Cost<-30
Tawfik[Tawfik$GameName=="$2,500 A WEEK FOR LIFE!",]$Cost<-5
Tawfik[Tawfik$GameName=="$200 Million Extravaganza",]$Cost<-20
Tawfik[Tawfik$GameName=="$200,000 JACKPOT",]$Cost<-5
Tawfik[Tawfik$GameName=="$200,000 TRIPLE PLAY",]$Cost<-5
Tawfik[Tawfik$GameName=="$250,000 PLATINUM PAYOUT",]$Cost<-5
Tawfik[Tawfik$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$Cost<-20
Tawfik[Tawfik$GameName=="$4,000,000 PLATINUM PAYOUT",]$Cost<-20
Tawfik[Tawfik$GameName=="$5,000,000 FORTUNE",]$Cost<-20
Tawfik[Tawfik$GameName=="$500,000 Anniversary Cash",]$Cost<-10
Tawfik[Tawfik$GameName=="$500,000 Jackpot",]$Cost<-10
Tawfik[Tawfik$GameName=="20X THE CASH!",]$Cost<-5
Tawfik[Tawfik$GameName=="BIG MONEY PLAYBOOK",]$Cost<-20
Tawfik[Tawfik$GameName=="CAROLINA BLACK",]$Cost<-5
Tawfik[Tawfik$GameName=="Diamonds & Gold",]$Cost<-10
Tawfik[Tawfik$GameName=="EXTREME MILLIONS",]$Cost<-30
Tawfik[Tawfik$GameName=="Ez Grand",]$Cost<-5
Tawfik[Tawfik$GameName=="GOLD",]$Cost<-5
Tawfik[Tawfik$GameName=="HIT $5,000",]$Cost<-10
Tawfik[Tawfik$GameName=="HOLIDAY MILLIONAIRE",]$Cost<-10
Tawfik[Tawfik$GameName=="JUMBO BUCKS",]$Cost<-10
Tawfik[Tawfik$GameName=="Lifetime Riches",]$Cost<-10
Tawfik[Tawfik$GameName=="LUCKY NO. 7",]$Cost<-10
Tawfik[Tawfik$GameName=="MEGA FORTUNE",]$Cost<-5
Tawfik[Tawfik$GameName=="MILLIONAIRE 7S",]$Cost<-10
Tawfik[Tawfik$GameName=="MONOPOLY FRENZY!",]$Cost<-5
Tawfik[Tawfik$GameName=="WIN IT ALL",]$Cost<-5
Tawfik[Tawfik$GameName=="ULTIMATE MILLIONS",]$Cost<-30
Tawfik[Tawfik$GameName=="WHEEL OF FORTUNE",]$Cost<-5
Tawfik[Tawfik$GameName=="Pick 4"|Tawfik$GameName=="Wild 8s",]$Cost<-1
```
```
```
```{r Bobby}
#Bobby Dean White
Bobby<-beforelottery[beforelottery$Fullname=="Bobby Dean White",]
Bobby$NumberToWin<-0
Bobby$Won<-0
Bobby$Cost<-0
Bobby[Bobby$GameName=="LUCKY NO. 7",]$Cost<-10
Bobby[Bobby$GameName=="Jingle Big Ol Bucks",]$Cost<-2
Bobby[Bobby$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$Cost<-20
Bobby[Bobby$GameName=="$200 Million Extravaganza",]$Cost<-20
Bobby[Bobby$GameName=="Cash Spectacular",]$Cost<-10
Bobby[Bobby$GameName=="$4,000,000 Cash Blowout",]$Cost<-20
Bobby[Bobby$GameName=="$100,000 TAXES PAID",]$Cost<-5
Bobby[Bobby$GameName=="Holiday Millions",]$Cost<-10
Bobby[Bobby$GameName=="RUBY RED 7s",]$Cost<-20
Bobby[Bobby$GameName=="Maximum Green",]$Cost<-10
Bobby[Bobby$GameName=="$4,000,000 GOLD BULLION",]$Cost<-20
Bobby[Bobby$GameName=="20X THE CASH",]$Cost<-5
Bobby[Bobby$GameName=="$120 MILLION CASH",]$Cost<-20
Bobby[Bobby$GameName=="JUMBO BUCKS",]$Cost<-10
Bobby[Bobby$GameName=="$200 MILLION BLOWOUT",]$Cost<-20
Bobby[Bobby$GameName=="ULTIMATE MILLIONS",]$Cost<-30
Bobby[Bobby$GameName=="MILLIONAIRE BUCKS",]$Cost<-20
Bobby[Bobby$GameName=="PLATINUM 7S",]$Cost<-10
Bobby[Bobby$GameName=="50X THE CASH!",]$Cost<-10
Bobby[Bobby$GameName=="$5,000,000 MEGA CASH",]$Cost<-20
Bobby[Bobby$GameName=="RUBY RED 7S",]$Cost<-20
Bobby[Bobby$GameName=="$50,000 DIAMOND DAZZLER",]$Cost<-2
Bobby[Bobby$GameName=="EXTREME MILLIONS",]$Cost<-30
Bobby[Bobby$GameName=="QUEEN OF HEARTS",]$Cost<-5
Bobby[Bobby$GameName=="100X THE CASH",]$Cost<-20
Bobby[Bobby$GameName=="$4,000,000 DIAMOND DAZZLER",]$Cost<-20
Bobby[Bobby$GameName=="$10,000,000 COLOSSAL CASH",]$Cost<-30
Bobby[Bobby$GameName=="$150 MILLION CASH EXPLOSION",]$Cost<-20
Bobby[Bobby$GameName=="$5,000,000 FORTUNE",]$Cost<-20
```
```
```
```{r Paul}
#Paul Julieus Kirkpatrick
Paul<-beforelottery[beforelottery$Fullname=="Paul Julieus Kirkpatrick",]
Paul$NumberToWin<-0
Paul$Won<-0
Paul$Cost<-0
Paul[Paul$GameName=="$300,000 JACKPOT",]$Cost<-5
Paul[Paul$GameName=="$5,000 LOADED",]$Cost<-10
Paul[Paul$GameName=="Wild 8s",]$Cost<-1
Paul[Paul$GameName=="50X THE CASH",]$Cost<-10
Paul[Paul$GameName=="Maximum Green",]$Cost<-10
Paul[Paul$GameName=="Cash Spectacular",]$Cost<-10
Paul[Paul$GameName=="JUMBO BUCKS",]$Cost<-10
Paul[Paul$GameName=="$1,000 MAYHEM",]$Cost<-10
Paul[Paul$GameName=="100X THE CASH",]$Cost<-20
Paul[Paul$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$Cost<-20
Paul[Paul$GameName=="ULTIMATE MILLIONS",]$Cost<-30
Paul[Paul$GameName=="50X THE CASH!",]$Cost<-10
Paul[Paul$GameName=="10th ANNIVERSARY MILLIONS",]$Cost<-10
Paul[Paul$GameName=="HOLIDAY MILLIONS",]$Cost<-10
Paul[Paul$GameName=="$250,000 DIAMOND DAZZLER",]$Cost<-5
Paul[Paul$GameName=="EXTREME MILLIONS",]$Cost<-30
Paul[Paul$GameName=="$5,000,000 MEGA CASH",]$Cost<-20
Paul[Paul$GameName=="Pick 4",]$Cost<-1
Paul[Paul$GameName=="Pick 3",]$Cost<-1
Paul[Paul$GameName=="Keno",]$Cost<-10
```
```
```
```{r Betty}
#Betty Carolynn Manning
Betty<-beforelottery[beforelottery$Fullname=="Betty Carolynn Manning",]
Betty$NumberToWin<-0
Betty$Won<-0
Betty$Cost<-0
Betty[Betty$GameName=="$500,000 Anniversary Cash",]$Cost<-10
Betty[Betty$GameName=="Carolina Gold",]$Cost<-10
Betty[Betty$GameName=="$5,000 A WEEK FOR LIFE!",]$Cost<-10
Betty[Betty$GameName=="$120 MILLION CASH",]$Cost<-20
Betty[Betty$GameName=="THE COLOR OF MONEY",]$Cost<-10
Betty[Betty$GameName=="$4,000,000 GOLD BULLION",]$Cost<-20
Betty[Betty$GameName=="CAESARS",]$Cost<-5
Betty[Betty$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$Cost<-20
Betty[Betty$GameName=="RED HOT 5S",]$Cost<-5
Betty[Betty$GameName=="LUCKY CLOVER",]$Cost<-2
Betty[Betty$GameName=="MILLIONAIRE 7S",]$Cost<-10
Betty[Betty$GameName=="$1,000,000 JACKPOT",]$Cost<-10
Betty[Betty$GameName=="$200,000 JACKPOT",]$Cost<-5
Betty[Betty$GameName=="$200 MILLION BLOWOUT",]$Cost<-20
Betty[Betty$GameName=="JOKERS WILD",]$Cost<-5
Betty[Betty$GameName=="50X THE CASH",]$Cost<-10
Betty[Betty$GameName=="$1,000 MAYHEM",]$Cost<-10
Betty[Betty$GameName=="ULTIMATE MILLIONS",]$Cost<-30
Betty[Betty$GameName=="GOLD 7S",]$Cost<-5
Betty[Betty$GameName=="100X THE CASH",]$Cost<-20
Betty[Betty$GameName=="$300,000 JACKPOT",]$Cost<-5
Betty[Betty$GameName=="$5,000 LOADED",]$Cost<-10
Betty[Betty$GameName=="Wild 8s",]$Cost<-1
Betty[Betty$GameName=="50X THE CASH",]$Cost<-10
Betty[Betty$GameName=="Maximum Green",]$Cost<-10
Betty[Betty$GameName=="Cash Spectacular",]$Cost<-10
Betty[Betty$GameName=="JUMBO BUCKS",]$Cost<-10
Betty[Betty$GameName=="$1,000 MAYHEM",]$Cost<-10
Betty[Betty$GameName=="100X THE CASH",]$Cost<-20
Betty[Betty$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$Cost<-20
Betty[Betty$GameName=="ULTIMATE MILLIONS",]$Cost<-30
Betty[Betty$GameName=="50X THE CASH!",]$Cost<-10
Betty[Betty$GameName=="$4,000,000 PLATINUM PAYOUT",]$Cost<-20
Betty[Betty$GameName=="HOLIDAY MILLIONS",]$Cost<-10
Betty[Betty$GameName=="$1,000,000 BONUS CASH",]$Cost<-10
Betty[Betty$GameName=="$5,000,000 MEGA CASH",]$Cost<-20
Betty[Betty$GameName=="ALL AMERICAN BUCKS",]$Cost<-3
Betty[Betty$GameName=="STRIKE IT RICH!",]$Cost<-5
Betty[Betty$GameName=="777",]$Cost<-5
Betty[Betty$GameName=="EXTREME MILLIONS",]$Cost<-30
Betty[Betty$GameName=="$10,000,000 COLOSSAL CASH",]$Cost<-30
Betty[Betty$GameName=="WIN IT ALL",]$Cost<-5
Betty[Betty$GameName=="BIG MONEY PLAYBOOK",]$Cost<-20
Betty[Betty$GameName=="$2,500 FRENZY",]$Cost<-10
Betty[Betty$GameName=="CAROLINA BLACK",]$Cost<-5
Betty[Betty$GameName=="$1,000,000 WIN IT ALL",]$Cost<-10
Betty[Betty$GameName=="Pick 4",]$Cost<-1
Betty[Betty$GameName=="PLATINUM 7S",]$Cost<-10
Betty[Betty$GameName=="MILLIONAIRE BUCKS",]$Cost<-20
```
```
```
```{r Beverly}
#Beverly Ann Collins
Beverly<-beforelottery[beforelottery$Fullname=="Beverly Ann Collins",]
unique(Beverly$GameName)
Beverly$NumberToWin<-0
Beverly$Won<-0
Beverly$Cost<-0
Beverly[Beverly$GameName=="MILLIONAIRE 7S",]$Cost<-10
Beverly[Beverly$GameName=="THE COLOR OF MONEY",]$Cost<-10
Beverly[Beverly$GameName=="50X THE CASH",]$Cost<-10
Beverly[Beverly$GameName=="$4,000,000 MULTIPLIER SPECTACU",]$Cost<-20
Beverly[Beverly$GameName=="ULTIMATE MILLIONS",]$Cost<-30
Beverly[Beverly$GameName=="$2,500 FRENZY",]$Cost<-10
Beverly[Beverly$GameName=="100X THE CASH",]$Cost<-20
Beverly[Beverly$GameName=="$500,000 Jackpot",]$Cost<-10
Beverly[Beverly$GameName=="$200 Million Extravaganza",]$Cost<-20
Beverly[Beverly$GameName=="$4,000,000 Cash Blowout",]$Cost<-20
Beverly[Beverly$GameName=="Cash Spectacular",]$Cost<-10
Beverly[Beverly$GameName=="$1,000,000 JACKPOT",]$Cost<-10
Beverly[Beverly$GameName=="$1,000 MAYHEM",]$Cost<-10
Beverly[Beverly$GameName=="10th ANNIVERSARY MILLIONS",]$Cost<-10
Beverly[Beverly$GameName=="EXTREME MILLIONS",]$Cost<-30
#"$" cant find
Beverly[Beverly$GameName=="$4,000,000 PLATINUM PAYOUT",]$Cost<-20
Beverly[Beverly$GameName=="$4,000,000 DIAMOND DAZZLER",]$Cost<-20
Beverly[Beverly$GameName=="JUMBO BUCKS",]$Cost<-10
Beverly[Beverly$GameName=="$10,000,000 COLOSSAL CASH",]$Cost<-30
Beverly[Beverly$GameName=="LUCKY NO. 7",]$Cost<-10
Beverly[Beverly$GameName=="$300,000,000 SUPREME RICHES",]$Cost<-30
```
```
```
```{r David}
#David Hughes Griffin
David<-beforelottery[beforelottery$Fullname=="David Hughes Griffin",]
unique(David$GameName)
David$NumberToWin<-0
David$Won<-0
David$Cost<-0
David[David$GameName=="HIT $5,000",]$Cost<-10
David[David$GameName=="ULTIMATE MILLIONS",]$Cost<-30
David[David$GameName=="100X THE CASH",]$Cost<-20
David[David$GameName=="JUMBO BUCKS",]$Cost<-10
David[David$GameName=="$1,000 MAYHEM",]$Cost<-10
David[David$GameName=="MILLIONAIRE 7S",]$Cost<-10
David[David$GameName=="EXTREME MILLIONS",]$Cost<-30
David[David$GameName=="$5,000,000 MEGA CASH",]$Cost<-20
David[David$GameName=="$4,000,000 PLATINUM PAYOUT",]$Cost<-20
David[David$GameName=="LUCKY NO. 7",]$Cost<-10
David[David$GameName=="$10,000,000 COLOSSAL CASH",]$Cost<-30
David[David$GameName=="$1,000,000 BACK SCRATCH",]$Cost<-10
David[David$GameName=="$4,000,000 DIAMOND DAZZLER",]$Cost<-20
David[David$GameName=="$150 MILLION CASH EXPLOSION",]$Cost<-20
David[David$GameName=="$300,000,000 SUPREME RICHES",]$Cost<-30
David[David$GameName=="$5,000,000 FORTUNE",]$Cost<-20
David[David$GameName=="Mega Millions",]$Cost<-2
```
```
```
```{r Margaret}
Margaret<-beforelottery[beforelottery$Fullname=="Margaret A Howell",]
unique(Margaret$GameName)
Margaret$NumberToWin<-0
Margaret$Won<-0
Margaret$Cost<-0
Margaret[Margaret$GameName=="CASINO RICHES",]$Cost<-5
Margaret[Margaret$GameName=="$200 Million Extravaganza",]$Cost<-20
Margaret[Margaret$GameName=="$5,000 A WEEK FOR LIFE!",]$Cost<-10
Margaret[Margaret$GameName=="$1,000 A WEEK FOR LIFE!",]$Cost<-2
Margaret[Margaret$GameName=="50X THE CASH",]$Cost<-10
Margaret[Margaret$GameName=="$1,000 MAYHEM",]$Cost<-10
Margaret[Margaret$GameName=="$200 MILLION BLOWOUT",]$Cost<-20
Margaret[Margaret$GameName=="$200,000 GOLD RUSH",]$Cost<-5
Margaret[Margaret$GameName=="50X THE CASH!",]$Cost<-10
Margaret[Margaret$GameName=="ULTIMATE MILLIONS",]$Cost<-30
Margaret[Margaret$GameName=="RUBY RED 7S",]$Cost<-20
Margaret[Margaret$GameName=="20X THE CASH!",]$Cost<-5
Margaret[Margaret$GameName=="CAROLINA MILLIONS",]$Cost<-10
Margaret[Margaret$GameName=="$2,500 A WEEK FOR LIFE!",]$Cost<-5
Margaret[Margaret$GameName=="Pick 4",]$Cost<-1
Margaret[Margaret$GameName=="Pick 3",]$Cost<-1
```
```
```
```{r simulation}
set.seed(50000)
Curtis$NumberToWin=0
Curtis$Won=0
Curtis$outPocket=0
JamesSumReturn<-random.sample.times(James[James$GameName!="Pick 4" & James$GameName!="Pick 3" & James$GameName!="Wild 8s",],1000)
CurtisSumReturn<-random.sample.times(Curtis[Curtis$GameName!="Pick 4" & Curtis$GameName!="Pick 3" & Curtis$GameName!="Wild 8s",],1000)+pick4Alg(Curtis[Curtis$GameName=="Pick 4" | Curtis$GameName=="Pick 3" | Curtis$GameName=="Wild 8s",],1000)
BobbySumReturn<-random.sample.times(Bobby[Bobby$GameName!="Pick 4" & Bobby$GameName!="Pick 3" & Bobby$GameName!="Wild 8s",],1000)
PaulSumReturn<-random.sample.times(Paul[Paul$GameName!="Pick 4" & Paul$GameName!="Pick 3" & Paul$GameName!="Wild 8s",],1000)+pick4Alg(Paul[Paul$GameName=="Pick 4" | Paul$GameName=="Pick 3" | Paul$GameName=="Wild 8s",],1000)
BettySumReturn<-random.sample.times(Betty[Betty$GameName!="Pick 4" & Betty$GameName!="Pick 3" & Betty$GameName!="Wild 8s",],1000)+pick4Alg(Betty[Betty$GameName=="Pick 4" | Betty$GameName=="Pick 3" | Betty$GameName=="Wild 8s",],1000)
BeverlySumReturn<-random.sample.times(Beverly[Beverly$GameName!="Pick 4" & Beverly$GameName!="Pick 3" & Beverly$GameName!="Wild 8s",],1000)
DavidSumReturn<-random.sample.times(David[David$GameName!="Pick 4" & David$GameName!="Pick 3" & David$GameName!="Wild 8s",],1000)
MargaretSumReturn<-random.sample.times(Margaret[Margaret$GameName!="Pick 4" & Margaret$GameName!="Pick 3" & Margaret$GameName!="Wild 8s",],1000)+pick4Alg(Margaret[Margaret$GameName=="Pick 4" | Margaret$GameName=="Pick 3" | Margaret$GameName=="Wild 8s",],1000)
TawfikSumReturn<-random.sample.times(Tawfik[Tawfik$GameName!="Pick 4" & Tawfik$GameName!="Pick 3" & Tawfik$GameName!="Wild 8s",],1000)+pick4Alg(Tawfik[Tawfik$GameName=="Pick 4" | Tawfik$GameName=="Pick 3" | Tawfik$GameName=="Wild 8s",],1000)
```
```
```
```{r topNine sum return all}
topNineSumReturn<-data_frame(Name=c("Winner 1","Winner 2","Winner 3","Winner 4","Winner 5","Winner 6","Winner 7","Winner 8","Winner 9"),"mean Instant"=c(mean(JamesSumReturn),mean(TawfikSumReturn),mean(CurtisSumReturn),mean(BobbySumReturn),mean(PaulSumReturn),mean(BettySumReturn),mean(BeverlySumReturn),mean(DavidSumReturn),mean(MargaretSumReturn)),"Minimum Cost Instant"=c(max(JamesSumReturn),max(TawfikSumReturn),max(CurtisSumReturn),max(BobbySumReturn),max(PaulSumReturn),max(BettySumReturn),max(BeverlySumReturn),max(DavidSumReturn),max(MargaretSumReturn)),"Maximum Cost Instant"=c(min(JamesSumReturn),min(TawfikSumReturn),min(CurtisSumReturn),min(BobbySumReturn),min(PaulSumReturn),min(BettySumReturn),min(BeverlySumReturn),min(DavidSumReturn),min(MargaretSumReturn)),"10% Percentile Instant"=c(quantile(JamesSumReturn,0.1),quantile(TawfikSumReturn,0.1),quantile(CurtisSumReturn,0.1),quantile(BobbySumReturn,0.1),quantile(PaulSumReturn,0.1),quantile(BettySumReturn,0.1),quantile(BeverlySumReturn,0.1),quantile(DavidSumReturn,0.1),quantile(MargaretSumReturn,0.1)),"90% Percentile Instant"=c(quantile(JamesSumReturn,0.90),quantile(TawfikSumReturn,0.90),quantile(CurtisSumReturn,0.90),quantile(BobbySumReturn,0.90),quantile(PaulSumReturn,0.90),quantile(BettySumReturn,0.90),quantile(BeverlySumReturn,0.90),quantile(DavidSumReturn,0.90),quantile(MargaretSumReturn,0.90)))
```
```
```
```{r bigwinner}
allPeople_select<-allPeople%>%select(Fullname,SellingRetailerName,count.x,count.y)%>%rename("WinningCount"=count.x,"StoreCount"=count.y)
allPeople_select<-allPeople_select%>%unique()%>%mutate(possibility=StoreCount/(WinningCount))
allPeople_select<-allPeople_select%>%group_by(Fullname)%>%mutate(entropy=-sum(possibility*log(possibility)))
allPeople_count=allPeople_select%>%group_by(WinningCount)%>%count(WinningCount)%>%mutate(SameWinCount=n)
allPeople_select=allPeople_select%>%left_join(allPeople_count,by="WinningCount")
bigWinner<-allPeople_select%>%filter(WinningCount>=20)%>%select(Fullname,SellingRetailerName,WinningCount,StoreCount,possibility,entropy)%>%rename(StoreWinCount=StoreCount)
bigWinner<-bigWinner%>%group_by(Fullname)%>%arrange(possibility)%>%mutate(HighestStoreProb=max(possibility))
bigWinner<-bigWinner%>%group_by(Fullname)%>%mutate(rank = rank(desc(possibility),ties.method = "random")) %>%arrange(rank)%>%ungroup()
bigWinner_pivoted<-bigWinner%>%pivot_wider(names_from = rank,values_from = possibility,id_cols = Fullname)
bigWinner_top5<-bigWinner_pivoted
bigWinner_top5$Rest = 0
for (a in 1:nrow(bigWinner_top5)){
  bigWinner_top5[a,]$Rest = sum(bigWinner_top5[a,7:87],na.rm = TRUE)
}
bigWinner_top5<-bigWinner_top5%>%rename("One"=`1`,"Two"=`2`,"Three"=`3`,"Four"=`4`,"Five"=`5`,"Six"=`6`)
bigWinner_top5<-bigWinner_top5%>%select(Fullname,One,Two,Three,Four,Five,Rest)
bigWinner_top5[is.na(bigWinner_top5)] <- 0
```
```
```
```{r see kmeans clusters}
set.seed(50000)
mvtop5_2cluster<-kmeans(bigWinner_top5[,2:7], 2)
mvtop5_5cluster<-kmeans(bigWinner_top5[,2:7], 5)
mvtop5_7cluster<-kmeans(bigWinner_top5[,2:7], 7)
bigWinner_top5$cluster = as.factor(mvtop5_5cluster$cluster)
temp1<-bigWinner_top5%>%right_join(topNine,by = "Fullname")
fviz_cluster(mvtop5_2cluster, data = bigWinner_top5[,2:7])
fviz_cluster(mvtop5_5cluster, data = bigWinner_top5[,2:7])
fviz_cluster(mvtop5_7cluster, data = bigWinner_top5[,2:7])
bigWinner_top5$cluster7 = as.factor(mvtop5_7cluster$cluster)
temp2<-bigWinner_top5%>%right_join(topNine,by = "Fullname")

bigWinner_top5$cluster2 = as.factor(mvtop5_2cluster$cluster)
temp3<-bigWinner_top5%>%right_join(topNine,by = "Fullname")

mvtop5_15cluster<-kmeans(bigWinner_top5[,2:7], 15)
bigWinner_top5$cluster15 = as.factor(mvtop5_15cluster$cluster)
temp4<-bigWinner_top5%>%right_join(topNine,by = "Fullname")

mvtop5_20cluster<-kmeans(bigWinner_top5[,2:7], 20)
bigWinner_top5$cluster20 = as.factor(mvtop5_20cluster$cluster)
temp5<-bigWinner_top5%>%right_join(topNine,by = "Fullname")

mvtop5_25cluster<-kmeans(bigWinner_top5[,2:7], 25)
bigWinner_top5$cluster25 = as.factor(mvtop5_25cluster$cluster)
temp5<-bigWinner_top5%>%right_join(topNine,by = "Fullname")
temp6<-temp5%>%select(Fullname,cluster15,cluster20,cluster25,cluster30,cluster35)
temp6$Fullname = c("Winner 1","Winner 2","Winner 3","Winner 4","Winner 5","Winner 6","Winner 7","Winner 8","Winner 9")
```
```
```
```{r see people in certain clusters}
#20
cluster20_16<-bigWinner_top5[bigWinner_top5$cluster20==16,]
cluster20_16<-unique(unique(beforelottery%>%right_join(cluster20_16,by = "Fullname")%>%select(Fullname,SellingRetailerAddress,One,Two,Three,Four,Five,Rest, cluster,cluster2,cluster7,cluster15,cluster20))%>%left_join(simulation_entropy,by="Fullname")%>%select(Fullname,One,Two,Three,Four,Five,Rest,cluster15,cluster20,`Estimate total money`,`Log Cost`,WinningCount,entropy))

#15
cluster15_9<-bigWinner_top5[bigWinner_top5$cluster15==9,]
cluster15_9<-unique(unique(beforelottery%>%right_join(cluster15_9,by = "Fullname")%>%select(Fullname,SellingRetailerAddress,One,Two,Three,Four,Five,Rest, cluster,cluster2,cluster7,cluster15,cluster20))%>%left_join(simulation_entropy,by="Fullname")%>%select(Fullname,One,Two,Three,Four,Five,Rest,cluster15,cluster20,`Estimate total money`,`Log Cost`,WinningCount,entropy))

#Combine 
cluster_9_16<-cluster15_9%>%full_join(cluster20_16,by="Fullname")

ggplot(cluster15_9)+geom_point(mapping =aes(x=`Log Cost`,y=entropy,color=cluster20))

#25
cluster25_2<-bigWinner_top5[bigWinner_top5$cluster25==2,]
cluster25_2<-unique(unique(beforelottery%>%right_join(cluster25_2,by = "Fullname")%>%select(Fullname,SellingRetailerAddress,One,Two,Three,Four,Five,Rest, cluster,cluster2,cluster7,cluster15,cluster20,cluster25))%>%left_join(simulation_entropy,by="Fullname")%>%select(Fullname,One,Two,Three,Four,Five,Rest,cluster15,cluster20,cluster25,`Estimate total money`,`Log Cost`,WinningCount,entropy))

#Curtis
cluster25_7<-bigWinner_top5[bigWinner_top5$cluster25==7,]
cluster25_7<-unique(unique(beforelottery%>%right_join(cluster25_7,by = "Fullname")%>%select(Fullname,SellingRetailerAddress,One,Two,Three,Four,Five,Rest, cluster,cluster2,cluster7,cluster15,cluster20,cluster25))%>%left_join(simulation_entropy,by="Fullname")%>%select(Fullname,One,Two,Three,Four,Five,Rest,cluster15,cluster20,cluster25,`Estimate total money`,`Log Cost`,WinningCount,entropy))

ggplot()+geom_point(mapping =aes(x=`Log Cost`,y=entropy),color="red",data = cluster25_2)+geom_point(mapping =aes(x=`Log Cost`,y=entropy),color="blue",data = cluster25_2)

mvtop5_30cluster<-kmeans(bigWinner_top5[,2:7], 30)
bigWinner_top5$cluster30 = as.factor(mvtop5_30cluster$cluster)
temp5<-bigWinner_top5%>%right_join(topNine,by = "Fullname")

#
cluster25_2<-bigWinner_top5[bigWinner_top5$cluster25==2,]
cluster25_2<-unique(unique(beforelottery%>%right_join(cluster25_2,by = "Fullname")%>%select(Fullname,SellingRetailerAddress,One,Two,Three,Four,Five,Rest, cluster,cluster2,cluster7,cluster15,cluster20,cluster25))%>%left_join(simulation_entropy,by="Fullname")%>%select(Fullname,One,Two,Three,Four,Five,Rest,cluster15,cluster20,cluster25,`Estimate total money`,`Log Cost`,WinningCount,entropy))
```
```
```
```{r graph}
set.seed(5000)
ggplot()+geom_point(mapping=aes(x=simulation_entropy$entropy,y=simulation_entropy$`Log Cost`),color="blue")+geom_point(mapping=aes(x=cluster25_2$entropy,y=cluster25_2$`Log Cost`),color="red")+ggtitle("Log Cost vs Entropy")+xlab("Entropy")+ylab("Log Cost")

ggplot()+geom_point(mapping=aes(x=simulation_entropy$entropy,y=simulation_entropy$`Log Cost`),color = "dark grey",alpha = 0.5,size = 0.7)+geom_point(mapping=aes(x=cluster25_2$entropy,y=cluster25_2$`Log Cost`),color="red")+geom_point(mapping=aes(x=cluster25_7$entropy,y=cluster25_7$`Log Cost`),color="blue")+ggtitle("Log Cost vs Entropy")+xlab("Entropy")+ylab("Log Cost") 

simulation_entropy_unique1<-simulation_entropy_unique%>%right_join(bigWinner_top5,by="Fullname")

ggplot()+geom_point(mapping=aes(x=simulation_entropy$entropy,y=simulation_entropy$`Log Cost`),color="white",size =0.5)+geom_point(mapping=aes(x=simulation_entropy_unique1$entropy,y=simulation_entropy_unique1$`Log Cost`,color=simulation_entropy_unique1$cluster25),size =0.5)+ggtitle("Log Cost vs Entropy")+xlab("Entropy")+ylab("Log Cost")+
  scale_colour_manual(guide="legend", breaks = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25),values = c("#8b4513","#228b22","#708090","#808000","#483d8b","#000080","#9acd32","#ff0000","#ffa500","#ffff00","#7cfc00","#8a2be2","#00ff7f","#dc143c","#00bfff","#0000ff","#da70d6","#ff7f50","#ff00ff","#1e90ff","#eee8aa","#b0e0e6","#ff1493","#7fffd4","#ffc0cb")) 

ggplot()+geom_point(mapping=aes(x=simulation_entropy_unique1$entropy,y=simulation_entropy_unique1$`Log Cost`),color=simulation_entropy_unique1$cluster25)+ggtitle("Log Cost vs Entropy")+xlab("Entropy")+ylab("Log Cost")

#Clean and orgnized the code a lokt so still working on the paper. @ thinks to discuss:1. see the graph 2. Should we find a better way to define the cost. (used to only use 1/possibility to win a big prize)

mvtop5_50cluster<-kmeans(bigWinner_top5[,2:7], 50)
bigWinner_top5$cluster50 = as.factor(mvtop5_50cluster$cluster)
temp5<-bigWinner_top5%>%right_join(topNine,by = "Fullname")

mvtop5_40cluster<-kmeans(bigWinner_top5[,2:7], 40)
bigWinner_top5$cluster40 = as.factor(mvtop5_40cluster$cluster)
temp5<-bigWinner_top5%>%right_join(topNine,by = "Fullname")

mvtop5_35cluster<-kmeans(bigWinner_top5[,2:7], 35)
bigWinner_top5$cluster35 = as.factor(mvtop5_35cluster$cluster)
temp5<-bigWinner_top5%>%right_join(topNine,by = "Fullname")
```
```
```
```{r}
beforelottery%>%right_join(cluster25_2,by = "Fullname")
topNine$Fullname
temp11<-data.frame(Paul$GameName,Paul$Cost)%>%rename("GameName"=Paul.GameName,"Cost"=Paul.Cost)
temp12<-data.frame(Curtis$GameName,Curtis$Cost)%>%rename("GameName"=Curtis.GameName,"Cost"=Curtis.Cost)
temp13<-data.frame(Tawfik$GameName,Tawfik$Cost)%>%rename("GameName"=Tawfik.GameName,"Cost"=Tawfik.Cost)
temp14<-data.frame(James$GameName,James$Cost)%>%rename("GameName"=James.GameName,"Cost"=James.Cost)
temp15<-data.frame(Bobby$GameName,Bobby$Cost)%>%rename("GameName"=Bobby.GameName,"Cost"=Bobby.Cost)
temp16<-data.frame(Betty$GameName,Betty$Cost)%>%rename("GameName"=Betty.GameName,"Cost"=Betty.Cost)
temp17<-data.frame(Beverly$GameName,Beverly$Cost)%>%rename("GameName"=Beverly.GameName,"Cost"=Beverly.Cost)
temp18<-data.frame(David$GameName,David$Cost)%>%rename("GameName"=David.GameName,"Cost"=David.Cost)
temp19<-data.frame(Margaret$GameName,Margaret$Cost)%>%rename("GameName"=Margaret.GameName,"Cost"=Margaret.Cost)

lotteryCost<-unique(rbind(temp11,temp12,temp13,temp14,temp15,temp16,temp17,temp18,temp19))

cluster25_2$Fullname

Reginald<-beforelottery[beforelottery$Fullname=="Reginald Keith Joyner",]%>%left_join(lotteryCost,by="GameName")

Reginald[Reginald$GameName=="$100 Million Cash Spectacular",]$Cost<-10
Reginald[Reginald$GameName=="$130 Million Blockbuster",]$Cost<-10

Penelope<-beforelottery[beforelottery$Fullname=="Penelope S Morgan",]%>%left_join(lotteryCost,by="GameName")
Penelope[Penelope$GameName=="$130 Million Blockbuster",]$Cost<-10
Penelope[Penelope$GameName=="Jumbo Bucks",]$Cost<-10

Hubert<-beforelottery[beforelottery$Fullname=="Hubert D Piver",]%>%left_join(lotteryCost,by="GameName")
Hubert[Hubert$GameName=="$100 Million Cash Spectacular",]$Cost<-10
Hubert[Hubert$GameName=="Jumbo Bucks",]$Cost<-10

Charles<-beforelottery[beforelottery$Fullname=="Charles Eugene Williams",]%>%left_join(lotteryCost,by="GameName")
Charles[Charles$GameName=="Super 7s",]$Cost<-5
Charles[Charles$GameName=="Jumbo Bucks",]$Cost<-10

Kevan<-beforelottery[beforelottery$Fullname=="Kevan Andrew Bytnar",]%>%left_join(lotteryCost,by="GameName")
Kevan[Kevan$GameName=="$200,000 Jackpot",]$Cost<-5

Eddie<-beforelottery[beforelottery$Fullname=="Eddie Dennis Beaver",]%>%left_join(lotteryCost,by="GameName")

Paul1<-beforelottery[beforelottery$Fullname=="Paul Jay Braun",]%>%left_join(lotteryCost,by="GameName")
Paul1[Paul1$GameName=="20X THE MONEY",]$Cost<-5

James1<-beforelottery[beforelottery$Fullname=="James Lynn Peachee",]%>%left_join(lotteryCost,by="GameName")

Paul2<-beforelottery[beforelottery$Fullname=="Paul Douglas Maxwell",]%>%left_join(lotteryCost,by="GameName")
Paul2[Paul2$GameName=="Jumbo Bucks",]$Cost<-10

Bernadette<-beforelottery[beforelottery$Fullname=="Bernadette Caldwell Mohamed",]%>%left_join(lotteryCost,by="GameName")

Howard<-beforelottery[beforelottery$Fullname=="Howard Brooks Helton",]%>%left_join(lotteryCost,by="GameName")
Howard[Howard$GameName=="$130 Million Blockbuster",]$Cost<-10
Howard[Howard$GameName=="Jumbo Bucks",]$Cost<-10
Howard[Howard$GameName=="$500 A WEEK FOR LIFE!",]$Cost<-10
Howard[Howard$GameName=="20X THE MONEY",]$Cost<-10
Howard[Howard$GameName=="Triple Tripler",]$Cost<-3
Howard[Howard$GameName=="Monte Carlo",]$Cost<-5

Latisha<-beforelottery[beforelottery$Fullname=="Latisha Tonette Cutler",]%>%left_join(lotteryCost,by="GameName")
Latisha[Latisha$GameName=="MONOPOLY MILLIONAIRES CLUB",]$Cost<-5
Latisha[Latisha$GameName=="$250,000 FORTUNE",]$Cost<-5
Latisha[Latisha$GameName=="MONOPOLY MILLIONAIRES CLUB",]$Cost<-5
Latisha[Latisha$GameName=="CAROLINA CASH",]$Cost<-5

Steven<-beforelottery[beforelottery$Fullname=="Steven W Morris",]%>%left_join(lotteryCost,by="GameName")
Steven[Steven$GameName=="$4,000,000 PLATINUM PAYOUT",]$Cost<-20

Cuarles<-beforelottery[beforelottery$Fullname=="Charles NA Alston",]%>%left_join(lotteryCost,by="GameName")
Cuarles[Cuarles$GameName=="TRIPLE PLAY",]$Cost<-5
```
```
```
```{r}
ReginaldSumReturn<-random.sample.times(Reginald[Reginald$GameName!="Pick 4" & Reginald$GameName!="Pick 3" & Reginald$GameName!="Wild 8s",],1000)+pick4Alg(Reginald[Reginald$GameName=="Pick 4" | Reginald$GameName=="Pick 3" | Reginald$GameName=="Wild 8s",],1000)

PenelopeSumReturn<-random.sample.times(Penelope[Penelope$GameName!="Pick 4" & Penelope$GameName!="Pick 3" & Penelope$GameName!="Wild 8s",],1000)

Paul1SumReturn<-random.sample.times(Paul1[Paul1$GameName!="Pick 4" & Paul1$GameName!="Pick 3" & Paul1$GameName!="Wild 8s",],1000)

HubertSumReturn<-random.sample.times(Hubert[Hubert$GameName!="Pick 4" & Hubert$GameName!="Pick 3" & Hubert$GameName!="Wild 8s",],1000)

CharlesSumReturn<-random.sample.times(Charles[Charles$GameName!="Pick 4" & Charles$GameName!="Pick 3" & Charles$GameName!="Wild 8s",],1000)

KevanSumReturn<-random.sample.times(Kevan[Kevan$GameName!="Pick 4" & Kevan$GameName!="Pick 3" & Kevan$GameName!="Wild 8s",],1000)

EddieSumReturn<-random.sample.times(Eddie[Eddie$GameName!="Pick 4" & Eddie$GameName!="Pick 3" & Eddie$GameName!="Wild 8s",],1000)

James1SumReturn<-random.sample.times(James1[James1$GameName!="Pick 4" & James1$GameName!="Pick 3" & James1$GameName!="Wild 8s",],1000)

Paul2SumReturn<-random.sample.times(Paul2[Paul2$GameName!="Pick 4" & Paul2$GameName!="Pick 3" & Paul2$GameName!="Wild 8s",],1000)

BernadetteSumReturn<-random.sample.times(Bernadette[Bernadette$GameName!="Pick 4" & Bernadette$GameName!="Pick 3" & Bernadette$GameName!="Wild 8s",],1000)+pick4Alg(Bernadette[Bernadette$GameName=="Pick 4" | Bernadette$GameName=="Pick 3" | Bernadette$GameName=="Wild 8s",],1000)

HowardSumReturn<-random.sample.times(Howard[Howard$GameName!="Pick 4" & Howard$GameName!="Pick 3" & Howard$GameName!="Wild 8s",],1000)

LatishaSumReturn<-random.sample.times(Latisha[Latisha$GameName!="Pick 4" & Latisha$GameName!="Pick 3" & Latisha$GameName!="Wild 8s",],1000)+pick4Alg(Latisha[Latisha$GameName=="Pick 4" | Latisha$GameName=="Pick 3" | Latisha$GameName=="Wild 8s",],1000)

StevenSumReturn<-random.sample.times(Steven[Steven$GameName!="Pick 4" & Steven$GameName!="Pick 3" & Steven$GameName!="Wild 8s",],1000)

CuarlesSumReturn<-random.sample.times(Cuarles[Cuarles$GameName!="Pick 4" & Cuarles$GameName!="Pick 3" & Cuarles$GameName!="Wild 8s",],1000)+pick4Alg(Cuarles[Cuarles$GameName=="Pick 4" | Cuarles$GameName=="Pick 3" | Cuarles$GameName=="Wild 8s",],1000)
```
```
```
```{r}
cluster2SumReturn<-data_frame(Name=c("Winner 10","Winner 11","Winner 12","Winner 13","Winner 14","Winner 15","Winner 16","Winner 17","Winner 18","Winner 19","Winner 20","Winner 21","Winner 22","Winner 23"),"mean Instant"=c(mean(ReginaldSumReturn),mean(PenelopeSumReturn),mean(Paul1SumReturn),mean(HubertSumReturn),mean(CharlesSumReturn),mean(KevanSumReturn),mean(EddieSumReturn),mean(James1SumReturn),mean(Paul2SumReturn),mean(BernadetteSumReturn),mean(HowardSumReturn),mean(LatishaSumReturn),mean(StevenSumReturn),mean(CuarlesSumReturn)),"Minimum Cost Instant"=c(max(ReginaldSumReturn),max(PenelopeSumReturn),max(Paul1SumReturn),max(HubertSumReturn),max(CharlesSumReturn),max(KevanSumReturn),max(EddieSumReturn),max(James1SumReturn),max(Paul2SumReturn),max(BernadetteSumReturn),max(HowardSumReturn),max(LatishaSumReturn),max(StevenSumReturn),max(CuarlesSumReturn)),"Maximum Cost Instant"=c(min(ReginaldSumReturn),min(PenelopeSumReturn),min(Paul1SumReturn),min(HubertSumReturn),min(CharlesSumReturn),min(KevanSumReturn),min(EddieSumReturn),min(James1SumReturn),min(Paul2SumReturn),min(BernadetteSumReturn),min(HowardSumReturn),min(LatishaSumReturn),min(StevenSumReturn),min(CuarlesSumReturn)),"90% Percentile Instant"=c(quantile(ReginaldSumReturn,0.1),quantile(PenelopeSumReturn,0.1),quantile(Paul1SumReturn,0.1),quantile(HubertSumReturn,0.1),quantile(CharlesSumReturn,0.1),quantile(KevanSumReturn,0.1),quantile(EddieSumReturn,0.1),quantile(James1SumReturn,0.1),quantile(Paul2SumReturn,0.1),quantile(BernadetteSumReturn,0.1),quantile(HowardSumReturn,0.1),quantile(LatishaSumReturn,0.1),quantile(StevenSumReturn,0.1),quantile(CuarlesSumReturn,0.1)),"10% Percentile Instant"=c(quantile(ReginaldSumReturn,0.9),quantile(PenelopeSumReturn,0.9),quantile(Paul1SumReturn,0.9),quantile(HubertSumReturn,0.9),quantile(CharlesSumReturn,0.9),quantile(KevanSumReturn,0.9),quantile(EddieSumReturn,0.9),quantile(James1SumReturn,0.9),quantile(Paul2SumReturn,0.9),quantile(BernadetteSumReturn,0.9),quantile(HowardSumReturn,0.9),quantile(LatishaSumReturn,0.9),quantile(StevenSumReturn,0.9),quantile(CuarlesSumReturn,0.9)))

cluster2SumReturn<-cluster2SumReturn%>%rbind(topNineSumReturn)
#Rerun for Penelope
```
```
```
```{r}
mean(simulation_entropy_unique$StoreCount)
sum(simulation_entropy_unique$StoreCount==1)
```
```
```
```{r}
MegaAlg<-function(tempName,Time){
  
  megaplier_number = c(2,3,4,5)
  megaplier_prob = c(1/3,1/2.5,1/5,1/15)
  
  AllProb = c(1/302575350,1/12607306,1/931001,1/38792,1/14547,1/606,1/693,1/89,1/37,1-(1/302575350+1/12607306+1/931001+1/38792+1/14547+1/606+1/693+1/89+1/37))
  X1Prize = c(1000002,1000000,10000,500,200,10,10,4,2,0)
  
  X2Prize = c(2000002,2000000,20000,1000,400,20,20,8,4,0)

  X3Prize = c(3000002,3000000,30000,1500,600,30,30,12,6,0)
  
  X4Prize = c(4000002,4000000,40000,2000,800,40,40,16,8,0)
  
  X5Prize = c(5000002,5000000,50000,2500,1000,50,50,20,10,0)
  
  sumReturn<-numeric(0)
  tempName$NumberofCost=0
  tempName$Won=0
  tempName$outPocket=0
  b<-0
  while(b < Time){
    for(a in 1:nrow(tempName)){
      if(tempName[a,]$PrizeAmount%in%c(1000000,10000)){
        #When multiplier == 1
        temp<-random.sample(X1Prize,AllProb)
        tempName[a,]$NumberofCost<-temp[1]*2
        tempName[a,]$Won<-temp[2]
      }else{
        multiplier = sample(megaplier_number,1,replace = TRUE,prob = megaplier_prob)
        if(multiplier == 2){
           temp<-random.sample(X2Prize,AllProb)
           tempName[a,]$NumberofCost<-temp[1]*3
           tempName[a,]$Won<-temp[2]
        }else if(multiplier == 3){
           temp<-random.sample(X3Prize,AllProb)
           tempName[a,]$NumberofCost<-temp[1]*3
           tempName[a,]$Won<-temp[2]
        }else if(multiplier == 4){
           temp<-random.sample(X3Prize,AllProb)
           tempName[a,]$NumberofCost<-temp[1]*3
           tempName[a,]$Won<-temp[2]
        }else if(multiplier == 5){
           temp<-random.sample(X3Prize,AllProb)
           tempName[a,]$NumberofCost<-temp[1]*3
           tempName[a,]$Won<-temp[2]
        }
      }
    }
    tempName<-tempName%>%mutate(outPocket=NumberofCost-Won-PrizeAmount)
    sumReturn<-append(sumReturn,-sum(tempName$outPocket))
    b=b+1
}
  return(sumReturn)
}
```
```
```
```{r}
ReginalMega = Reginald[Reginald$GameName=="Mega Millions",] #10000
PenelopeMega = Penelope[Penelope$GameName=="Mega Millions",] #600
Paul1Mega = Paul1[Paul1$GameName=="Mega Millions",] #600
DavidMega = David[David$GameName=="Mega Millions",] #1500

r = MegaAlg(ReginalMega,1000)
ReginaldSumReturn1 = ReginaldSumReturn+r
p = MegaAlg(PenelopeMega,1000)
PenelopeSumReturn1 = PenelopeSumReturn+p
p1 = MegaAlg(Paul1Mega,1000)
Paul1SumReturn1 = Paul1SumReturn+p1
d = MegaAlg(DavidMega,1000)
DavidReturn1 = DavidSumReturn+d
```
```
```
```{r}
Cash5Alg<-function(tempName,Time){
  sumReturn<-numeric(0)
  tempName$NumberToWin=0
  tempName$Won=0
  tempName$outPocket=0
  b<-0
  prize = c(50000,250,5,1,0)
  lotteryProb = c(1/749398,1/4163,1/119,1/10.5,1-(1/749398+1/4163+1/119+1/10.5))
  while(b < Time){
    for(a in 1:nrow(tempName)){
      temp<-random.sample(prize,lotteryProb)
      tempName[a,]$NumberToWin<-temp[1]
      tempName[a,]$Won<-temp[2]
    }
    tempName<-tempName%>%mutate(outPocket=NumberToWin*1-Won-PrizeAmount)
    sumReturn<-append(sumReturn,-sum(tempName$outPocket))
    b=b+1
}
  return(sumReturn)
}
```
```
```
```{r}
PenelopeCash5 = Penelope[Penelope$GameName=="Cash 5",] #79093
p5 = Cash5Alg(PenelopeCash5,10)
```
```
```
```{r}
PowerAlg<-function(tempName,Time){
  
  AllProb = c(1/292201338,1/11688054,1/9131291,1/36525,1/14494,1/580,1/701,1/92,1/38,1-(1/292201338+1/11688054+1/9131291+1/36525+1/14494+1/580+1/701+1/92+1/38))
  X1Prize = c(1000001,1000000,50000,100,100,7,7,4,4,0)
  
  sumReturn<-numeric(0)
  tempName$NumberofCost=0
  tempName$Won=0
  tempName$outPocket=0
  b<-0
  while(b < Time){
    for(a in 1:nrow(tempName)){
        #When multiplier == 1
        temp<-random.sample(X1Prize,AllProb)
        tempName[a,]$NumberofCost<-temp[1]*2
        tempName[a,]$Won<-temp[2]
    }
    tempName<-tempName%>%mutate(outPocket=NumberofCost-Won-PrizeAmount)
    sumReturn<-append(sumReturn,-sum(tempName$outPocket))
    b=b+1
}
  return(sumReturn)
}
```


```{r}
PenelopePower = Penelope[Penelope$GameName=="Powerball",] #1000000
ppower = PowerAlg(PenelopePower,1000)
```
```
```
```{r}
nrow(simulation_entropy_unique[simulation_entropy_unique$WinningCount>=20,])
nrow(simulation_entropy_unique)
1/292201338+1/11688054+1/9131291
```
```
```
```{r}
ReginalMega = Reginald[Reginald$GameName=="Mega Millions",] #10000
PenelopeMega = Penelope[Penelope$GameName=="Mega Millions",] #600
Paul1Mega = Paul1[Paul1$GameName=="Mega Millions",] #600
DavidMega = David[David$GameName=="Mega Millions",] #1500
mean(r)
mean(p)
mean(p1)
mean(d)
PenelopeCash5 = Penelope[Penelope$GameName=="Cash 5",] #79093
p5 = Cash5Alg(PenelopeCash5,10)
mean(p5)
mean(ppower)

PenelopeSumReturn1 = PenelopeSumReturn1+ppower
print(mean(ReginaldSumReturn1))
print(quantile(ReginaldSumReturn1,0.1))
print(quantile(ReginaldSumReturn1,0.9))

print(mean(PenelopeSumReturn1))
print(quantile(PenelopeSumReturn1,0.1))
print(quantile(PenelopeSumReturn1,0.9))

print(mean(Paul1SumReturn1))
print(quantile(Paul1SumReturn1,0.1))
print(quantile(Paul1SumReturn1,0.9))


print(mean(DavidReturn1))
print(quantile(DavidReturn1,0.1))
print(quantile(DavidReturn1,0.9))
```